---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: networking
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: cloudflare-ddns-configmap
    files:
      - ./cloudflare-ddns.sh
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
