apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:E8wDFRjK9vAXD5gK41p66klNdZJNHA==,iv:MIHdIzS25doxjy7iLlb+krM+dNNogXctctIzQtvHogs=,tag:IMCM6HZ/kf52z5LaDa1ZHA==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:ur4Sp5qBAwq0+vAV9ROVUu6DZq1u5yHfMvvHk1AK8wDcIos47A==,iv:PuITJ9KQ6/WDeY7nV7tr/c5F9SsVQd0WnvbiljtudJc=,tag:0YmmpBAHD4nivwbeEM5K6A==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:+y40605fydXyL3N7d4e+2k97Ug7B,iv:r6ysNv8Iq43uHO+4U9kn20aWowDSg65saHGhdzooawU=,tag:JNFqKkH+EG/8C2gYSU4AnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxV3hYTjFNaGh5cjJDdUll
            eHJ3cC9keGRMcExCbHBjZDlIWWVSTjZIU2xJClMzVkVQMy8vVHlRTXZyMklkeWln
            YlJuRWNsSHorUlNLaVo0R0ZsVzZjZTgKLS0tIDA5aDRwc0EzSTBYazZhSjdYNDZ2
            anVMSnp5akdLTGVESElkd0VZMzllU2sK2laGY6kaNnLCSna4aZlwLUznSVWsiQAl
            7sy+SqrXjFHPPbqlH6CNSUNBVxnKrW/yTs47IwLQ4u1F7xpCN2+vaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T05:39:11Z"
    mac: ENC[AES256_GCM,data:r2u90s17HczLxBDA5w+epjesj0f0kZE25ZDYpW9CT7qh4DgQ1zRU7wDA0C+auVy5uxfbGtBPajrJOyHECI9lV2tTvzC0ZUazAmlH1mrKy5KuX1tnjzdKmQmg2+ZMSx0A+ddqSyHBUE9NtzhtQpu1386ckv411rKgUHsHIGsOK2s=,iv:uhTtdjGiBd/xpQfKykKlg7wEKasK7xRS1xHx4N0rXpo=,tag:7yztKUGiR5KLl+DCyffg6g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
