apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:oaYTTmZr7rZGTpMcwm0n5OuRtMLK5A==,iv:IAT3F7+ShRq0uCfDQgN8vN+853IXqqbWWryy7XQBUnQ=,tag:VTEE+H2aGaMT5W6u0oOAog==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:/e8XpoaNGcc5lqTr2/efkxzevjz6nbZiLzqoiQSX114C3shwdA==,iv:FysabIOIE9Z/7jjvkeMnTRYEp/VkBwiI9hUatP2Kuac=,tag:AzJhNHughSTDbqiNH+Ji+w==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:0sRV5sZw2mbCAuwVS9Qft88IJpF6,iv:LpbL+tEABF37DeV3uaklbcdKyPN2YbFSpazJv/s3AlE=,tag:2XK6wX/JlJ9pndSiFRl6fQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONTJXODJEamt1RzVyaFJ0
            V1dyTVl3RlR6VVZFVnhKRHovcTR1UWZNRkQ0CkgvaU4yT1haYzIvTWFWQ1JhRzJp
            ZHZxUzZUVnhCN3hFVmlpTWQzUW5rWjgKLS0tIFJqcFl2VnVwaFUzL1FCWHRkanlQ
            VDEwUHFhVHNqK1VjUW9WczlQT0llYlEKkdEgfNqxMN0tyasz7Lw/jJSBpfXLHdX5
            iJoY/8aVRMfhxCEoXBAaRcXtAgaC/5+/sb1JoSe7eZOF0beRPF1HDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-20T04:33:51Z"
    mac: ENC[AES256_GCM,data:C/c9osMA5VQMiXeCM1DKmDGxZ9ATH80dGrJB6oqSYmiifS+F9KT/Zw1fsWrpExlTa3Pza779X2EbLE/WoG8/xVfETQGJyg0/69dQulk832sTcH5odDSlB9F+AFDlZczzmv75VghU1asWifz1mqFwwdtL6eA8dPJI+8gqC++4aeE=,iv:yn6pi3qV4M1U41bXVMnJohf+Mef3cM7+Db+ZjXX47d0=,tag:vzFKszJFtcbBPkE2fcXl1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
