apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:b3f7Hx37KKFSxTaqGa6JJ5PkSlzK1w==,iv:PzLgbF7SOcB5D9Q4VhLLxS/SzVgShKC4n0Nx3SKsVBM=,tag:Ad0eNcGcJBWcRq6GM5toTw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:S7k2iFU2EMEIoVCpPR1+1TbjODZM63WXWkI6mQaL9PxfrnJbeA==,iv:K69zW1RqDgbORG/wb9MXc8n7pO9pdJhhYKbBATkbQAk=,tag:E460WrQzQ2W9KOJl5rhuQQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:reEvpkTxs7ncEvIEIemUqV3LuulC,iv:fMk2yope/cnA5Suz8wI9iB7qKB2kxxPkDPrB9Gf+cJE=,tag:tdFxGpxgM1QLr/lx5vR5Xw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiekJqck82MXVzNUJqOTN6
            Um0zdXpZUlM5R2ZDb1o5NDkyb3dCTVlwL2tRClBnRXdUR0VaY0lwL2RNTzFKUG8r
            QnF1R2dkb3pvS3UrbWJYdmpxNVJBNGcKLS0tIGp2RTI2WldSS2tGcnpqWjV5YmZn
            enVYbGJRU0NSK2dTMXZDTTFSOGE0Uk0K5KYw9EtJHbOxrf9n0Rf70h/Pp5aa7OEi
            1BLR46wo2L8Q2aiw1pn7AFDs/AUU6GAXl4pgIFOHhHojYp0vuTW7Jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T19:43:19Z"
    mac: ENC[AES256_GCM,data:4FylpfvO81mK82cd0XQeHwFpzMngibCQtkemG7I/TID9zSAc6RVDBjcYcKQI28KN0IawT2h1MJIwVs93QtXcc3+Tp2GB/wwO5f525j3mo8Xirr0fg50lbVt2jr7qjTYV9OSY1MzlYkcHJudiZKRUNMP11utT+W2gNMqAtA0sUAU=,iv:j4sfJrfe94T53DdSysooFwx3qp7WuMNcFbanqhlHNRM=,tag:+WfIAHp1vbODHMboG+D3dQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
