apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns-secret
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:uOwnkce9L8jczFwYFA8vQwFtSn7aZg==,iv:MJwJNPJ5J4iR16rswUgepTcp0MR5QwksZzhHRf0jmdI=,tag:KX5SFYyuTo4eb5k19xnjZQ==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:5xS/vAwdpE4wdEgEiFKhoV3DrG6lhoxzUHXOj9iy15P24XS9kw==,iv:B5TN/4OjNmsRZzbYxI3MLJVxLNutwkW4XDNAObUdCks=,tag:u+ErLA5SD4OolHw2i62wqQ==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:vYASAwlOIokQcdppV0wuWd96wYHD,iv:IBSHIHk3w1ZRgHkkOWYa2EyG8TrAFr9FFUuKle+eVjQ=,tag:lTtjYT66exb6SWhr2WWZUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4M2tKRytFUUh3ZlBVSmZL
            bVlqdXZ5dDZsdS9KbSt0WWdKTjZ1U3V6T3hjCnpBeE9DdXNOblFMQ1VyQml3VzFs
            Z1R4SFd5aEg1cVB6NmZaa2YyR0I3eHMKLS0tIEF5NWxlYlJvaE5HZkJKVTV3bVVz
            YTRUMExVaU1pRXIzOVVlZ1FYRUlsWU0Kh3V6m6VAb1irXAjXAcGyq1N29rPFU7oN
            RFdgR1lkioP/UnV3u7PF96jQTdWn3/oHCVNN6kTXUUC9A/l+SzFCVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T15:21:41Z"
    mac: ENC[AES256_GCM,data:CcdZqYBGYVKqCz7jenU0XcW5wTlDgo+4h5Ddo9crSguvUIT0JqpxsuhPi8Fja5dBHFfmU7HokRvyXECjCXPrVCStWGziuFTkwbl0gG6uVtzf/BeLNPU+7rTYXOXoU3Es2giTtwNyvTuQysC3dXY9mFonWXPe8iSZy7kbWm7Yd7w=,iv:zboX+OaS40geb7kQqmfyd0iQBCxEC4MBqWqYrK9z0Ck=,tag:DwQJ8k+PmvDrJ/Cucb9HlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
