kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:zhToojudEae5TGdw6WdUgw==,iv:5vAy9uQxEwjitQSiqxpqDIeRUPDH2Ps7vfNSzwhTAvc=,tag:I7CAoNQXBEaL/Q5RW7M0wg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Nlmi3r4LrDpjBxETZzCLlxNXdwKapkxN6XNCEb+5weQ=,iv:fIvnDFz3X326WdX2IP/B3y1nCcUN56U9j9oe3uq4NQk=,tag:iUVprWCe+oKe7CpULEZG6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T06:33:27Z"
    mac: ENC[AES256_GCM,data:V1YVBRbO6IKAlP+1uMJpniF4jRSBOe7okDpuN9DyJwDuBLLITj3oMOwvCgTV3yXIJky/T+h1o3jHYbPPIjLK7yyxc+4zcjztUaEezqo5GBawctXsORNIUyaeQ5cBJwk6Xy5/5CODD6Mnu2E4eIX1UtOSRPyrS8u+azETnj3Mv/Y=,iv:bf36zwbDK1FUk5tuhs4rr0K7hhK4ZHNNRx3lKxyQ99M=,tag:DhrQ034nKzpz4/82zKxWZg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
