kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:nYVxJUKwboxCjM1PWODQcw==,iv:FTLb04qr/kzQtEMdD9jmKCIYriMEA0MYui2kstNL1Xk=,tag:SJFpOGisLU4bE3RNjq8sDw==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:I7P/PFZP6sgSCTxMuT9Lx1aNZoZhnTYK6BGcP5lH3WE=,iv:RjqUO80piNZzGrzMWGs0WCICpIESX/6NFIl/0WEvxHM=,tag:AWqMjpmOZnP9Q56Mbt0JOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-07T04:24:16Z"
    mac: ENC[AES256_GCM,data:3JEAz4xw1eeKpROGrtb0iGVKYSA4ho4Wr2MJoYCSPdXHIHt7ShxK36uqnTh0Ol05FbIHNOE0JLdCXNVydVqxyQvhUM70p3Wtr8KHxGgeVOPmJOE/qsKuhAE4i0tgsKElDMhjQ45WxFmCi9v37kcvkEjXoHU2J9RIcEMbII/8w2Q=,iv:v2IDuWdBVbAcCXMl3vKHDz7p86Cc7LxKkA1cj/chzyE=,tag:MwbYPwcbbjfEs+x5ZMl0Pw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
