kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:XW5XsdYVo3iFRKEdXq+jscU5hhU=,iv:WGC5WJ2+KrdQyszKr0IjjhIxub0bsMsj1exEnooGDUE=,tag:oVkgzGf1TvmWl+Z3aFeA3Q==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Pp9kViqAufJqId385hdktTVCudw=,iv:KQVYKsQ5KmysLSzP2pa8dZmotCSA7ud2F/SO1qWxYrU=,tag:HjwhHi4kb2BOvI7zGRt5eg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T03:12:21Z"
    mac: ENC[AES256_GCM,data:NiuFhchCYh0UE+Y3jrPkBSPtPC/j3Ls1TsJSVaWvD5QFAo2UGShL1dGnE8lBfBESbPINdhzvYdvp7sxn7ol37bnSOCmRYmqllOg1veh7lVQtJ8kF2dnswcV9rW9Jw5yNnDsj4c22evuwbslj6U1zLErDBUGhJU1j0xwbwEvc2aw=,iv:g4Nq2LG/908NQeAoT1mYr9rDMdLXuBdInZId5ZTiE4w=,tag:nrp0y5TrOGJIm4hX3tvplg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
