kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:zhToojudEae5TGdw6WdUgw==,iv:5vAy9uQxEwjitQSiqxpqDIeRUPDH2Ps7vfNSzwhTAvc=,tag:I7CAoNQXBEaL/Q5RW7M0wg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Nlmi3r4LrDpjBxETZzCLlxNXdwKapkxN6XNCEb+5weQ=,iv:fIvnDFz3X326WdX2IP/B3y1nCcUN56U9j9oe3uq4NQk=,tag:iUVprWCe+oKe7CpULEZG6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T07:20:30Z"
    mac: ENC[AES256_GCM,data:EMkrm4j2WJl5g189AphoiwMzB5WWqK+8zBj8zwOoxs3BjXQgGiXnxLZJChBZpptJ5z8WcuAldvD11u2vhFOo7K73gjU3ISp9Hxn3xER8Tj5R/mGeRgvziO4xiZHCmH8jKQmrkFJVV5II96MK8lCy1nV8vzK/Jll3ZYEzOepVd+E=,iv:cwFNqf4N904Q1Jtrw5kheHoRjMscDGwF3oQEqPfAeq4=,tag:KFgPVB86piAG7jwwe75lrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
    name: app-secret
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:CEbH8IDTCKfEsA==,iv:2PZ1wXgpHMSbQGUle31v3OWiyTpnxfbw7ruwad4mXsc=,tag:kGw5fogsiA3sY7ipF9BtUA==,type:str]
    password: ENC[AES256_GCM,data:GDJAZZAP1Nvu6frw21vPmZVu,iv:F56Ty2tkFCPb5AG+FPNI/HGA1i3PtPs3tL7alGvKfok=,tag:kssdoJ+d9RVUMeGVIwTvIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T07:20:30Z"
    mac: ENC[AES256_GCM,data:EMkrm4j2WJl5g189AphoiwMzB5WWqK+8zBj8zwOoxs3BjXQgGiXnxLZJChBZpptJ5z8WcuAldvD11u2vhFOo7K73gjU3ISp9Hxn3xER8Tj5R/mGeRgvziO4xiZHCmH8jKQmrkFJVV5II96MK8lCy1nV8vzK/Jll3ZYEzOepVd+E=,iv:cwFNqf4N904Q1Jtrw5kheHoRjMscDGwF3oQEqPfAeq4=,tag:KFgPVB86piAG7jwwe75lrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
