kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-minio
    namespace: database
stringData:
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:zhToojudEae5TGdw6WdUgw==,iv:5vAy9uQxEwjitQSiqxpqDIeRUPDH2Ps7vfNSzwhTAvc=,tag:I7CAoNQXBEaL/Q5RW7M0wg==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Nlmi3r4LrDpjBxETZzCLlxNXdwKapkxN6XNCEb+5weQ=,iv:fIvnDFz3X326WdX2IP/B3y1nCcUN56U9j9oe3uq4NQk=,tag:iUVprWCe+oKe7CpULEZG6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T06:31:30Z"
    mac: ENC[AES256_GCM,data:fpb/XOj94sHxi8qHF/tJR5+QtfTjUSc/uRmJ9SLAxSJMuwmNlu9QWgJW8jzLIFqv8tD9ALIMGKynC8L+8ixes4/eoy1BQ3ux7QURs1S+BTLjQRV7ofDfxKbISdFMPYl+mwBmsSdwgYKq1Tqzl9/f2G9qrl2frOVb5/I+3MO1xS0=,iv:cW8lyTBQMGXrfvLNqvBSvNOanoDOvF352ti3E4ebyhc=,tag:Z9XZVP41Nt7yMp25G/S3zg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: postgres-superuser
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:yi9/P+g=,iv:X/yFoq9r0hAS32aSmneFgW6rumAeS9+UaKCEHL+9ktc=,tag:i143H67dlFjG7foYF5Ndeg==,type:str]
    password: ENC[AES256_GCM,data:hFh1jxJHdb2/,iv:efCBzeiCH8RaIA9xQa3o3/0RZORWDHcZlhEEKD1MGNA=,tag:3CIH6fdvnrQpbrkxRzE7ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-09T06:31:30Z"
    mac: ENC[AES256_GCM,data:fpb/XOj94sHxi8qHF/tJR5+QtfTjUSc/uRmJ9SLAxSJMuwmNlu9QWgJW8jzLIFqv8tD9ALIMGKynC8L+8ixes4/eoy1BQ3ux7QURs1S+BTLjQRV7ofDfxKbISdFMPYl+mwBmsSdwgYKq1Tqzl9/f2G9qrl2frOVb5/I+3MO1xS0=,iv:cW8lyTBQMGXrfvLNqvBSvNOanoDOvF352ti3E4ebyhc=,tag:Z9XZVP41Nt7yMp25G/S3zg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
