---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./kube-vip/ks.yaml
  - ./local-path-provisioner/ks.yaml
  - ./metrics-server/ks.yaml
  - ./reloader/ks.yaml
  - ./node-feature-discovery/ks.yaml
