---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cluster-apps-flux-webhooks
  namespace: flux-system
spec:
  path: ./kubernetes/apps/flux-system/addons/webhooks
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 3m
