---
creation_rules:
  - path_regex: provision/.*\.sops\.ya?ml
    unencrypted_regex: "^(kind)$"
    age: >-
      age1l7dulnc9q3dsr6dfqgfec2mfufc0zckrntzqkfx8rvhzj9prfajq8jmztu
  - path_regex: cluster/.*\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    age: >-
      age1l7dulnc9q3dsr6dfqgfec2mfufc0zckrntzqkfx8rvhzj9prfajq8jmztu
