---
version: "3"

vars:
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  CLUSTER_DIR: "{{.PROJECT_DIR}}/cluster"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/provision/ansible"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/provision/terraform"

env:
  KUBECONFIG: "{{.PROJECT_DIR}}/provision/kubeconfig"

includes:
  ansible: .taskfiles/ansible.yml
  flux: .taskfiles/flux.yml
  format: .taskfiles/format.yml
  lint: .taskfiles/lint.yml
  pre-commit: .taskfiles/pre-commit.yml
  terraform: .taskfiles/terraform.yml

tasks:
 kubeconfig:
    desc: Remotely fetch kubeconfig from k3s
    cmds:
    - rsync --verbose --progress --partial --rsync-path="sudo rsync" ubuntu@192.168.178.81:/etc/rancher/k3s/k3s.yaml ./kubeconfig
    - sed -i 's/127.0.0.1/192.168.178.81/g' kubeconfig
    - sed -i 's/default/k3s-gitops/g' kubeconfig
    - chmod go-r kubeconfig
    silent: true
