apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: winklercloud-de
  namespace: default
spec:
  secretName: winklercloud-de-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-staging
  dnsNames:
  - '*.winklercloud.de'
  - winklercloud.de  