kind: ENC[AES256_GCM,data:6wN0GfpN,iv:ncVxE7Qk94zxLmMA5jJHx4lC8hg8EZVijhr1C6aYmUM=,tag:2UzHXDSd4yt4pgt81Lq/DA==,type:str]
ansible_user: ENC[AES256_GCM,data:ozirvQ==,iv:7Y1LXw0Fy3bcJBXfL2L+spFjs5exUSNs/j724f8FORQ=,tag:HexB+IUZHSkMgYyiW7VcGw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:rjjpcV0=,iv:iANRD9KVfNk5g5ci9ocSmXS6b5pSjokzdyF6rrm+H6k=,tag:qTFbDY8SLf0JrN1iRMmhUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzZ0FoK2ZGY3lHOUc4MFd4
            Vy93Y2greUhVUjFPc0RiYko1U3l4YklaRlFjCmRBbEk5Szd4Mk05dnEyZnhwQ3ll
            dDhmZk9GRStIYUZJRWxXQzBweE9rZnMKLS0tIFlnVnJXK1NRRDg4SXZpcFdBVG5K
            Y1J6QXpPM2NzMGtxNFBsUEJGMjVMRUEK5NwRrmJdRYqCOtpq6gugfNIQYGId2zgy
            bS7VC70vuZcmc9nB8ie8AzEu8YoisuMGWP1Bc8yyJNGVVjBYff0cDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T03:08:43Z"
    mac: ENC[AES256_GCM,data:PgUwvqV/KZWvFxTma/I0T+hb2wNwTflJpaFJMrfJfhdlSARVgKyF7KLnLgCS32NSDHEgJgVMvioKddMVHljXbhTSNpJmnKoBA7BDoFU18VGyrD5NnCu3L65Bv5B5NoGOTPcOYT8pum6EqeTIqtIKlPppzXw5oS512if7EHpHEak=,iv:qMf5czQad7uvdE2asBbv+OWlFWdYmcXv4efCe5kPBGc=,tag:LFKRpTBfueccAw+6F9HVKw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
