kind: ENC[AES256_GCM,data:0C0gIYfu,iv:ktvUF9uk10HVZCTcg7wfnv2aCm3yVPScKQAaVsZs1oM=,tag:i+nnjwDpXqzOmw6gZPlb7w==,type:str]
ansible_user: ENC[AES256_GCM,data:zdmJbA==,iv:gyjwf1JougZ1+Z84ABK+ZFnqiKfDr1drXB1FH5Z+oMk=,tag:ePQ5WCeX1LU/PrdWeg5F2w==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:AvM1Cn0=,iv:cdnEGQPkBC5I6lmGNHdtSCvfZucg1sDObOVIxLg2tsw=,tag:W/Ez4ubZnvvQp8w8s2hR9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bTkzc25vZVhVQmZxVitl
            a0U2ZXZTdjc5eVR3MkZHdlFJOHBjMDQwY0JZCm1MTkxDdGlrUW9BeGF0Q1liekQv
            TEVzay9PRmFnZTFRRi9KNmdORzhNam8KLS0tIHQwc0E2RGkwMkltZERMRTNicU5j
            Y3JRSVBMcmMvTDFtNWErSEY0Z1hSQmMKK5KBa5sq4YmtMKKAo43CEWNqXiqei0yg
            rqZBwwPgE6I4HZWeOYaNoyIbkm9aKoWGLurvN+FK2UvoAMSF+Rgecg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T21:01:06Z"
    mac: ENC[AES256_GCM,data:c7Vpnp68g4eHaHFHdkCcb/W33j92nv4YcbhKBdJQN3bPH0KzM4oQ6HW2wrq+vuD4DBmkrs3caGm6EeDLtphoQres9jSzADNEu2qOZDKDfQx/ymII/MTBb/5DqorFvceIEsxRRVXCkdlbBexnB+eKdkgc0VU2fCBUhV6Sx0EnWSc=,iv:GhrlkmN0C2DbAiVioB5g3+lhEsXN3pCCQWtPfa8tNGo=,tag:9M4gOjn+GxI+sPdZdCffIA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
