kind: ENC[AES256_GCM,data:Wj1FtiVZ,iv:oIdqD1ywisB4FDjBnj4eFBz2wyaXCq4KyskU/0a9ie4=,tag:0SbLLWsuO1bCcY6uj51Qag==,type:str]
ansible_user: ENC[AES256_GCM,data:Wda/xA==,iv:aPfMzOR7VSulXYX7xesAn5LiKOYGQ7V4WCn2NesUTzI=,tag:uPgu1ryaB9Q9OMGW0sjWJw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:HBIBJ4Q=,iv:oYsG5VFxpL84wa7LDy37ISmf2YtAuRUaHvp/5UnL0Po=,tag:NwTGO1rDAM7cOH1KlWi8IQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5VTQwaG0vVXhKQ0svVmxz
            aktQWW1kcHp5eXE1TG0vdkdCZCs3RDNReTBVCnUzTmFSNnIyZTRUemliUFFlSis0
            WlZRSEhFOWpnbnU5YlZhOXU4OGdFNlUKLS0tIEsrWjEzMlVNUGF0aXA2RVVYY01s
            Mm9jVms2N3U2TU9ab1NBMXhxVWE0bm8K6PCTgkfvP9Xv/F3qvJlsr6SCrscrR8tI
            /oWK4ZF12T3XakpO6Qhk+23gh1UPYQ3Nf0kPYsAAfQbqPd2Wut0qGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T07:16:56Z"
    mac: ENC[AES256_GCM,data:4G3F+XdzDchvXpKt8y+6B6vY97YNk0gbV/o3GLUYs2Ao+DoVdvjbyj2lWsfYNQfQBuxneIxdCl6YZhbeOm7dyFw4occXiX28g7q59YDeD92IAFXL1fUBLSMEP6bKgElzNzl0yixrIoZS5GXeuOt7aFrXDjvQLhy4nFLZQ2mqB2k=,iv:5iXgQkcbwmD0x2hmVw6iALi+pz5o3y/2KOfUaxzc4kY=,tag:N9YH4x7EAeuBJ6zYKFkfzA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
