kind: ENC[AES256_GCM,data:L/YV3Rix,iv:57zcuS8r87rVtRo3Mib7X/sxW8/R8/gdjWxxWANG/xE=,tag:Q5l6P9EOElkhnaSdX9fXHg==,type:str]
ansible_user: ENC[AES256_GCM,data:o0CCCg==,iv:Xltjosp5IoPZN8LBcVTqM4cLE4dIafY34CXEhK2Q6Bs=,tag:U+fPZvIYwJRIPJdmWitNdg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:oG8df9U=,iv:xj1AEzFCzkuLS9qAGpIIqxLD1IrPDvzEImihm56vYFs=,tag:9Miv6u8HMgu1CRwfaSWGbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIejBZaVE4MnU3dHBweUp0
            Y00yaDRBbnp3YWREUG9DREgweTJ1clM3R3djCnFkQWtlTEcwM1E3bXgxQjFUa0wy
            OEQ5RG0zSU5TaTVJNDd4Uy9XZWdXQjAKLS0tIGdTNlhvV0UvY0dNZjNDNnE4RVFQ
            bVN0WlNCY1hCalpxYVgxMEN3ZzdpZFEKcNOUe39dMuFH25AlgaSnH+Gz5APRbc1a
            a5VUoIUXFXh+0EgdVGiZ0BhRyR4YseUuWXcbnzcFfmBa2zqifsBlOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T21:01:06Z"
    mac: ENC[AES256_GCM,data:bLlIyH0liiZ3smID1k7AO8mwOM6I99i/Pi2H1NLLcJiOOpSM5x5rUgMJzRw7d8qkHBIc6lj4KhtY13MY7h0dPMvqq8m5dL2Z+k/oUaA8NEcQfjMhRLozsAJ/r7a0R7nqFkveeteMSbrAN7Ro8WwUCQKKnMRm0ReAERD65avZe44=,iv:4NixvPuezx3NohKNsIknbIYRFWnw+HUk8UJfdBUwo8M=,tag:PfFqnkBHrHUeaHMrr1jGAA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
