---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app adguard-home
  namespace: networking
spec:
  releaseName: *app
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    interval: 2m
    # logLevel: debug
    provider: cloudflare
    env:
      TZ: ${TIMEZONE}
    service:
      dns-tcp:
        enabled: true
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: ${LB_ADGUARD_IP}
        annotations:
            metallb.universe.tf/allow-shared-ip: adguard-home-svc
            hajimari.io/icon: shield-link-variant
            hajimari.io/appName: Adguard Home
      dns-udp:
        enabled: true
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: ${LB_ADGUARD_IP}
        annotations:
            metallb.universe.tf/allow-shared-ip: adguard-home-svc
    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/icon: adguard-home
          external-dns.alpha.kubernetes.io/hostname: dns01.${SECRET_DOMAIN}.
          external-dns.alpha.kubernetes.io/target: prx02.${SECRET_DOMAIN}.
        hosts:
          - host: &host dns01.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
            - *host
    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.10.10
        path: /mnt/Volume1/k3s
        subPath: adguard-home/config
        mountPath: /opt/adguardhome/conf
        accessMode: ReadWriteMany
        size: 1Gi
        retain: true
      data:
        enabled: true
        type: nfs
        server: 192.168.10.10
        path: /mnt/Volume1/k3s
        subPath: adguard-home/data
        mountPath: /opt/adguardhome/work
        accessMode: ReadWriteMany
        size: 1Gi
        retain: true


    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: adguard-home-secret
