---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app adguard-home
  namespace: networking
spec:
  releaseName: *app
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: adguard/adguardhome
      tag: v0.107.26
    env:
      TZ: ${TIMEZONE}
    service:
      main:
        primary: true
        ports:
          http:
            port: &port 3000
      dns:
        enabled: true
        type: LoadBalancer
        externalTrafficPolicy: Local
        # annotations:
        #   metallb.universe.tf/loadBalancerIPs: "${LB_ADGUARD_IP}"
        ports:
          dns-tcp:
            enabled: true
            port: &dns-port 53
            protocol: TCP
            targetPort: &dns-target-port 53
          dns-udp:
            enabled: true
            port: *dns-port
            protocol: UDP
            targetPort: *dns-target-port
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
          hajimari.io/enable: "true"
          hajimari.io/icon: "shield-check"
        hosts:
          - host: &host adguard.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host

    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.10.10
        path: /mnt/Volume1/k3s
        subPath: adguard-home/config
        mountPath: /opt/adguardhome/conf
        accessMode: ReadWriteMany
        size: 1Gi
        retain: true
      data:
        enabled: true
        type: nfs
        server: 192.168.10.10
        path: /mnt/Volume1/k3s
        subPath: adguard-home/data
        mountPath: /opt/adguardhome/work
        accessMode: ReadWriteMany
        size: 1Gi
        retain: true