---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app paperless
  namespace: document
spec:
  releaseName: *app
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  dependsOn:
    - name: dragonfly
      namespace: database
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.13.0
    env:
      COMPOSE_PROJECT_NAME: paperless
      # USERMAP_UID: 1500 # User document
      # USERMAP_GID: 1500 # Group documents
      # PAPERLESS_CONSUMPTION_DIR: "/consume"
      PAPERLESS_FILENAME_FORMAT_REMOVE_NONE: "true"
      PAPERLESS_OCR_LANGUAGES: eng deu
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_FILENAME_FORMAT: '{correspondent}/{document_type}/{created_year}-{created_month}-{created_day}_{title}_{asn}'
      PAPERLESS_FILENAME_DATE_ORDER: YMD
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
      PAPERLESS_CONSUMER_POLLING: 60
      PAPERLESS_OCR_MODE: redo
      PAPERLESS_OCR_CLEAN: clean
      PAPERLESS_PORT: 8000
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: paperless-secrets
            key: PAPERLESS_ADMIN_PASSWORD
      PAPERLESS_REDIS: redis://dragonfly.database.svc.cluster.local:6379
      PAPERLESS_TASK_WORKERS: 2
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      # PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_URL: dokumente.${SECRET_DOMAIN}
    service:
      main:
        ports:
          http:
            port: 8000
        type: LoadBalancer
        loadBalancerIP: "${LB_PAPERLESS_IP}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          hajimari.io/icon: mdi:barcode-scan
        hosts:
        - host: &host "dokumente.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
          tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        type: nfs
        server: "${LOCAL_LAN_TRUENAS}"
        mountPath: /usr/src/paperless/data
        path: /mnt/Volume1/document/data
      media:
        enabled: true
        type: nfs
        server: "${LOCAL_LAN_TRUENAS}"
        mountPath: /usr/src/paperless/media
        path: /mnt/Volume1/document/media
      consume:
        enabled: true
        type: nfs
        server: "${LOCAL_LAN_TRUENAS}"
        mountPath: /usr/src/paperless/consume
        path: /mnt/Volume1/document/consume
      export:
        enabled: true
        type: nfs
        server: "${LOCAL_LAN_TRUENAS}"
        mountPath: /usr/src/paperless/export
        path: /mnt/Volume1/document/export
    resources:
      requests:
        cpu: 25m
        memory: 3Gi
      limits:
        memory: 7Gi

