# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: paperless
    namespace: document
stringData:
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:5s5IEGw=,iv:HVkem5kSujPNXfIw28d/c3P/mqVp770kiOJyU46mh4A=,tag:68hCTeeRKNXQqz3PQWMWcQ==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:LTJZcnOEsgDxlPHbmb8=,iv:srqpEo4kvr8IkYL8EXmZlSQPZAFSa97DUH1xsPWuA7I=,tag:sO1Rl6nVo7Xo099iXuPIWg==,type:str]
# PAPERLESS_SECRET_KEY: ZdBxR8MKjKg9sR9GJFDnnvjhpZgcGKh5GfSexufjZQKEfNdosV
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-02T17:24:51Z"
    mac: ENC[AES256_GCM,data:v2QMWNMa3QRFd0dpln1m6efHMrfHmlJEl/WNHWmHliaD5it+MjcrrRdZdbnaDuRAQt6dgtO3MWPRVhXTnfssnSTzwZNMkLYdeSERWnNoQyd54tPc/Is14ZoJSmhKrJ7AGunrXnUOKG44hhWo9bSq4pmJST0EDq2BiUTZvoSrUSs=,iv:c/tL5g0x3TMyKg3q/clsT9TApRQVgKC/4MD3Ot0iyok=,tag:fahtgFN7e/KkveO++OmeTA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
