---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app vaultwarden
  namespace: security
spec:
  releaseName: *app
  interval: 15m
  chart:
    spec:
      chart: kah-common-chart
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/k8s-at-home/vaultwarden
      tag: 1.25.2
    env:
      DATA_FOLDER: "config"
      SIGNUPS_ALLOWED: false
      WEBSOCKET_ENABLED: true
      WEBSOCKET_ADDRESS: 0.0.0.0
      WEBSOCKET_PORT: 3012
      DOMAIN: https://bitwarden.${SECRET_DOMAIN}
      ADMIN_TOKEN: ${SECRET_VAULTWARDEN_ADMIN_TOKEN}
      SMTP_HOST: "smtp.sendgrid.net"
      SMTP_SECURITY: force_tls
      SMTP_PORT: 465
      SMTP_USERNAME: "apikey"
      SMTP_PASSWORD: "${SECRET_SENDGRID_API_KEY}"
      SMTP_AUTH_MECHANISM: "Login"
    service:
      main:
        ports:
          http:
            port: &port 80
          websocket:
            enabled: true
            port: &websocket-port 3012
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          hajimari.io/icon: "form-textbox-password"
          external-dns.home.arpa/enabled: "true"
        hosts:
          - host: "bitwarden.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  port: *port
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: *port
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: *websocket-port
        tls:
          - hosts:
              - "bitwarden.${SECRET_DOMAIN}"
            secretName: "bitwarden-tls"

    persistence:
      config:
        enabled: true
        storageClass: nfs
        accessMode: ReadWriteOnce
        size: 10Gi
