---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app paperless
  namespace: document
spec:
  releaseName: *app
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 0.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: redis
      namespace: database
  values:
    controller:
      replicas: 2
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/paperless-ngx/paperless-ngx
      tag: 1.8.0
    nameOverride: paperless
    fullnameOverride: paperless
    env:
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      #PAPERLESS_CONSUMPTION_DIR: "/consume"
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_OCR_LANGUAGES: deu eng
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_FILENAME_FORMAT: '{document_type}/{correspondent}/{created_year}'
      PAPERLESS_FILENAME_DATE_ORDER: YMD
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: paperless-secrets
            key: PAPERLESS_ADMIN_PASSWORD
      PAPERLESS_REDIS: redis://redis-master.database:6379
      PAPERLESS_TASK_WORKERS: 2
      PAPERLESS_THREADS_PER_WORKER: 2
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      #PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000      

    service:
      main:
        ports:
          http:
            port: &port 80
        type: LoadBalancer
        loadBalancerIP: "${LB_PAPERLESS_IP}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "dokumente.${DOMAIN_INTERNAL}"
        hosts:
        - host: "dokumente.${DOMAIN_INTERNAL}"
          paths:
          - path: /
            pathType: Prefix
            service:
                port: *port
    persistence:
      # -- Configure persistence for data.
      # @default -- See values.yaml
      data:
        enabled: true
        type: nfs
        server: 192.168.10.10
        path: /mnt/Volume1/document/data
        accessMode: ReadWriteMany
      # -- Configure persistence for media.
      # @default -- See values.yaml
      media:
        enabled: true
        type: nfs
        server: 192.168.10.10
        path: /mnt/Volume1/document/media
        accessMode: ReadWriteMany   
      # -- Configure volume to monitor for new documents.
      # @default -- See values.yaml
      consume:
        enabled: true
        type: nfs
        server: 192.168.10.10
        path: /mnt/Volume1/document/consume
        mountPath: /usr/src/paperless/consume
        accessMode: ReadWriteMany
      export:
        enabled: true
        type: nfs
        server: 192.168.10.10
        path: /mnt/Volume1/document/export
        mountPath: /usr/src/paperless/export
        accessMode: ReadWriteMany
    addons:
      redis:
        enabled: true
        architecture: standalone
