---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: paperless
  namespace: document
spec:
  releaseName: paperless
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: paperless
      version: 8.6.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: paperless
    fullnameOverride: paperless
    env:
      USERMAP_UID: 1000
      USERMAP_GID: 1000     
      PAPERLESS_CONSUMPTION_DIR: "/consume"
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_FILENAME_FORMAT: "{document_type}/{correspondent}/{create_year}-{create_month}-{correspondent}-{title}-{tag_list}"
      PAPERLESS_FILENAME_DATE_ORDER: YMD
      PAPERLESS_CONSUMER_DELETE_DUPLICATES: "true"
      PAPERLESS_CONSUMER_RECURSIVE: "true"
      PAPERLESS_ADMIN_USER: admin
      PAPERLESS_ADMIN_PASSWORD: admin@123
      PAPERLESS_REDIS: redis://redis:6379
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: "${LB_PAPERLESS_IP}"
        externalTrafficPolicy: Local
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
        - host: "paperless.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "paperless.${SECRET_DOMAIN}"
          secretName: "paperless-tls"

    persistence:
      # -- Configure persistence for data.
      # @default -- See values.yaml
      data:
        enabled: false
        mountPath: /usr/src/paperless/data
        emptyDir:
          enabled: false
        # type: pvc
        # existingClaim: nfs-document-pvc
        # subPath: data
      # -- Configure persistence for media.
      # @default -- See values.yaml
      media:
        enabled: false
        mountPath: /usr/src/paperless/media
        emptyDir:
          enabled: false
        # type: pvc
        # existingClaim: nfs-document-pvc
        # subPath: media
      # -- Configure volume to monitor for new documents.
      # @default -- See values.yaml
      consume:
        enabled: false
        mountPath: /usr/src/paperless/consume
        emptyDir:
          enabled: false
        # type: pvc
        # existingClaim: nfs-document-pvc
        # subPath: consume
      export:
        enabled: false
        mountPath: /usr/src/paperless/export
        emptyDir:
          enabled: false
        # type: pvc
        # existingClaim: nfs-document-pvc
        # subPath: export
    redis:
      enabled: true
      architecture: standalone
