# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: paperless-secrets
    namespace: document
stringData:
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:LTJZcnOEsgDxlPHbmb8=,iv:srqpEo4kvr8IkYL8EXmZlSQPZAFSa97DUH1xsPWuA7I=,tag:sO1Rl6nVo7Xo099iXuPIWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-17T07:52:26Z"
    mac: ENC[AES256_GCM,data:V01SBEszQkj1Jt0tsskNHM6Qp70X4msYFd7WT3a5kkOXtt6HvADjWnZA3iaQPqcdzQHkCYK3lKTDCxiyWaWzYzllo77CRETZqhu7oKB7k5XEe0wErIkDTNAfoSY+uqaXoJ0lXGIiAX81Mx8JBV8u0htddZJEPyAjS4ajTA0wQ7o=,iv:8zRdt1NiHl+OOySJ1AIjExXobeanoRbCfadzT9hE5Vc=,tag:mAjH0dBUMrpaCp/a0oVIrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
