# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: paperless-test-secret
    namespace: document
stringData:
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:LTJZcnOEsgDxlPHbmb8=,iv:srqpEo4kvr8IkYL8EXmZlSQPZAFSa97DUH1xsPWuA7I=,tag:sO1Rl6nVo7Xo099iXuPIWg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-17T08:29:41Z"
    mac: ENC[AES256_GCM,data:pVXKIQJPDcmLMW1+uxM+AbakNWAo7ggFiY9w5HpVpS+VHmlMDcUW3zt6IGkX4wiLrScK6Fk+CWZudWoh3nx+c3JRSincKYoNxX3c2lOk5RPWLP13ESxRnRAKZgNRFzOvMq38X8UZFiIBqeLgH8eblviXsbGsM6vdJ9DffiqTny4=,iv:AybBL0wNBPtOX8HuZZqwI2k/MrPwnXtcQ5xG8QmXAwQ=,tag:mwxIZ0nA1wzVF28wfuYY3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
