#jinja2: trim_blocks: True, lstrip_blocks: True
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: nfs.csi.k8s.io
parameters:
  server: ${LOCAL_LAN_TRUENAS}
  share: /mnt/Volume1/kubernetes
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]

