# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-creds
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:wRYmm/I=,iv:636mMs2vQYlio8DAhaRVM9nH/f9M2v5ygSLHNLw6bBo=,tag:irKKH/isCYAbjEU2uXyQvA==,type:str]
    admin-password: ENC[AES256_GCM,data:SahSNC9Bwu1N,iv:eGbwSy9F+PekKf+r70/LHDEukes4BI1892Wf0OYpW4c=,tag:VGj1HiMKSHPZxjtrDL/Vrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-21T02:25:40Z"
    mac: ENC[AES256_GCM,data:VXcbvFzP8csCzAuXOGX60LQU60dXilksJNK0DJFn47xNLnOyBfQGKInRxmOkemzxvvgazEgMf8UXZxtn3AUp0Cl2idxwP2Wk2FvHWZoy+zzaVOnsb2xxi/iJ3VCpqr8ZPI/VkzvjVqtub/Rlsrx+0+Q7JqlBayhWRqESWdD+Qig=,iv:rcueXiO0EDMwwi1M/iiJb9TYWFrZOwg2UgoyRcd7rPU=,tag:0tZDjH7i6xUBLnytC/9ksQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
