apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:mJnmdp4=,iv:Nll/dSQPb5iheTh52taVgCWLksMFjAz2XbHpHOOG22c=,tag:F6nHdhc4PyRruMeezmbeaA==,type:str]
    admin-password: ENC[AES256_GCM,data:CBjx4Sc=,iv:p9YDQvrfCbMfMQlnQ/NZliNwtqnpnSQTpDyuArVPPW8=,tag:Ec560MrQqHkqz0gPQBvccw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsamlHWUEvd09RV0JsM2ls
            MmRPMWwrT2pSdDNpTnBOL2pZczNtTkU4K2drClQxcW5tSzFoa2RwVkhERFpzZCs1
            SEw0SjdNZzZkZGM2bnNvcmQyblZTNlEKLS0tIEZOZm45WUUyNldPUDB6ekxoOGRY
            aFBKY3AwNExNYUZ0QUdrZUNoaXBLZDQK0S3NbCLBJTww/7QFtT3wC0qa99DP3srS
            V1JvgM9D80hIePmDChkbvBef4Una02EUOQqJWxkX4h4IV+vg+wm6Dg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T09:50:15Z"
    mac: ENC[AES256_GCM,data:4FaZTax0VZM+SoESheo4brQnJQLCCyyD+Ulel/9i8Qpm6OSn7oCVBpelDqVuQudAZBLMMSiDCnB71vy4dX+U2uDqnbaN9OBP0dlMMOLugdJsVr8Wcc/zxoQdqkps1sLk4oPJhT4HhHKlFakgnMvv4S2h9A9Ama4s0208arWGSjo=,iv:gXDrQFEg/l0lefEld6uxqbxUtGStpTxoMM6XwDAmF2I=,tag:X1EjV0sR+8BRAdpT0T2AEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
