apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
stringData:
    admin-user: ENC[AES256_GCM,data:3/5TpLg=,iv:LjNB0Vi+0XJ5surPGDDFXp806DmRB2NCyIABmFHc/Yk=,tag:H7LyzvMtsPRI152sLrpz3w==,type:str]
    admin-password: ENC[AES256_GCM,data:/+Azzcc=,iv:x6iif3D8QlkQSYrLBwQvzzJv3Sdfi+8z3zjhvpxD3Yw=,tag:wW1d6FPrQxgQt427n0m5ag==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlWmFlTThRbW5xakhaVXZn
            b0VUa2hqKzY1N0RTZUwwMlpCVDY4UkVIUkhVCi9FL3FIVGNibnpSTzhnYVhGMVc2
            Sk9nYWhWSFBRM09qY2J1Y1NIdnpvWFEKLS0tIHJ2RFhZMVcwUFUyTHNiaStpZURu
            VUNiMkZoNlE2ZTBmc1dnNm9CVXNHTUEKh/O5HsE82hJvzG2kh5mUbyWcLBU8OxuF
            OXWjtfgCWcpBRb9K3xwMep1r7rTei46rRHEwYmqyhV3vaKay/3PH9g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T03:08:45Z"
    mac: ENC[AES256_GCM,data:+sCd4w8PKN0ru337zz4E9Y8SXNTRslx5j0OOL5EhfcOPZnYUwomcmC6chFaSYQyiaiv4AE3xgM7jiG3q2R6W/5HgG9bGBfQaL3o8fFZskditIAcNz4qmpetB3kd1EzVD7c5SxrdJo4HeExLxHHK50adK1cwJL2bzaEvlsF6jEao=,iv:nQFxYE2qvgoV2ryFpvR4ypU/dFH54JmuFcPWFH7VlBE=,tag:ejkwoPrareRVbsh3lLZ/Lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
