# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    redis-password: ENC[AES256_GCM,data:qQyXoK4Iy4CWffBmauA=,iv:Ek1IvFAD7nJDsTZV6T63D34g91HHN5kET5fkI8KT/8Y=,tag:zlOv6f5Aj00q3t7l7qK4lw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-16T05:31:47Z"
    mac: ENC[AES256_GCM,data:etY2VHeX2yJO7SZt3PY+OE/x2V2/0qoijPYD7vFe3EBYPBDFMALnG44DQP17mXHw5A8FY/YFa4csYH1BHb5Ymv2Ktv1zsRwuyc3ndcl6jM/0l7KgfD6KXDZNlS46pMWvcqlmeL+sB1sL5Jkzj4tBOVlPKDCu3yvzlxeBxiqj77g=,iv:SwktSrHz08VsFLQuTTOKlbdgg8vw2rmj8hn5tTOvyCc=,tag:PeiUS5JD/9YjvYQhydszuQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
