---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: kube-system
resources:
  - ./rbac.yaml
  - ./daemonset.yaml
labels:
  - pairs:
      kustomize.toolkit.fluxcd.io/prune: disabled
