---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dragonfly
  namespace: flux-system
spec:
  interval: 1h
  url: oci://ghcr.io/dragonflydb/dragonfly/helm/dragonfly