apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:8XTL+/MY3T3cG5N0veBvYKoAxw1NoAIPQTrWEGr7YHPCC72hdUBZhg==,iv:mKv3nImogiX6t9mvOfJ4zdwiQBPPPkhhK3zx9pFV/7U=,tag:wAy01IvqZUzF33WQQ7vXvw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBK09GUkVoQWhHYUNpd2lN
            RmRGbGFyUW16cThrdEZCaXVReUdCWnBNc25RCjRRTGFFLzBneFhlRzhXUHdsYTU5
            cnQyN1FONDRuY0oxc1ZrLzE5ZjBRaVUKLS0tIEliNmozaGdOdnNVeGd3TURMeDJ5
            L0F0THNNcnRkR0N1a1FYMVpNZm5mbFUKjjBYq+2hO+o4J3XoPu/UOr81IgsLMd4F
            SpTF3kvgA1rw/+brYgSa+FrwE3o4VEtcLc0/EJppYbBBIcpvbWh+xA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T15:21:41Z"
    mac: ENC[AES256_GCM,data:RSXqZIdPft9uGR2XH2u7udPCZk2/e3bgxLLpA0t5geSL1dA2N1hPO8+olssL1hMI08NM60CCIvsRTrs10dL4ODLWt15E0u3TRm1qvUF8T4zZbpfiJSDJE7wWkXHtRfPTycqNcnSTWudHm1VJXelEpBwo63gypbn/9wLCDGgPcrk=,iv:CZLZB4agVQ1n/NMi1fhFc/Xt8S+x7nvFl0XBGRXXiLk=,tag:1oehBMup+2tRhE/hsTHRRg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
