apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:DHZXnEu9YmQBxTsQJbJzO7TaZK7KOO/U+GOtvPIeRhgGkkdO/4ZKBQ==,iv:EyztE9XY5ZTAfl2daPgOfCd7gUwjqhIa6g9rr/5jEb8=,tag:u4qDU5dBIilrRIJ6zToK/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQXBHQ3RVc2lpTWxZNzhZ
            T3lKZ0E1M2VkdjQwY2RQWEtaTUN3Rlc4VEFnClkrWkhBcVpwcExVVHlUSkNhTCtD
            UnlHdytDbDY4a0ZYNG0xblFXZlI2QTQKLS0tIEcwTHU0d2U4eG9aNHd6cUNVdzBC
            NHhzcDRIK3U0S3QyVjhTTDhmcG52clEKrkjuYhtP+zH3uzyM7iKNUToQsFIg55Oi
            +sHtKYHwgpx00PavynDFExaT26zz6srb7K2DOBzV0pX2Lc7HClWbSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T07:16:56Z"
    mac: ENC[AES256_GCM,data:N/BsnCpEXG1x2XVCPmS1nRhxw2PH+iY7ff8jDixFpIxik5FXZNT3KDSMnay2x4zQyMIhiBGzP919ZjNZ8zOVccOP6G2Nk8nV3aAcfOTX6nh0Tt3IAE8sLkkeTAm7PL6nKEvyPVCflWu6H7ZnqHDj2BAwydDFkH6O+JNYJwE+vq0=,iv:JQn4mCK8DXUvx5RSkzt0CjtEwy/C3JluBU8/6jtOJq4=,tag:04d5HFKLW+3gU37cvWeEyA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
