apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:31XvPNmQXDCqbQETdZ763uz9dqaaXY9n9L6SrHp8PHLMr1bDyGlAzg==,iv:WR5SkHaGiUFl9fk2xsCORR2cc7vzFLmdb60Bilt+lGA=,tag:/7QcXSP0Bl/WrJo+kmzDNQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaTGkxL2VFWG41bTVncDNT
            U2k1MnEwVk05cUxBUWZVS1VsSllnenluR3g4Cm5ua21qUW9Nb3ZEdEVMU3VLVGxs
            aXNMRWVmNDhkcFF0YndTZnFJcG1wZkEKLS0tIGpSQlRWb2l6RlVLbnVSb2h2UU56
            SDYrNDBUd0lGbSt0K2hnRUZvR2g2NjgKeVvgrAqESIobzKFyHwg6RJju7Yu5LDyZ
            cL48lriet2SfJWs6UyP0zKK1o6Xg7wbLSjnK02Ri1h8p3d3JYwPjdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T16:13:35Z"
    mac: ENC[AES256_GCM,data:4+Rsh5l/tTbbE7MFlH2dFch1b9qSa4VnEHbKk6gUvTDoADJdWqVIplbcKBFC/w9BbwICwcjWB7zzQSqQz/r6IkMNxv+eyxmOlzhIVSpsle/ZdS93rg4e/LO1Q7+8nNpQkJ5SyfxM9y9r9O2/rh9MvYGniTZnkI4q5lySGzgaroM=,iv:r0pL63aut1EanxTvXEwcqSqFLlxfzzTX4SIk5UOA7og=,tag:5Md3Yy7YRUMeoHwmLifH9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
