---
apiVersion: source.toolkit.fluxcd.io/v1beta2   
kind: HelmRepository
metadata:
  name: tika-charts
  namespace: flux-system
spec:
  interval: 30m0s
  url: https://apache.jfrog.io/artifactory/tika
  timeout: 3m0s