kubernetes:
  children:
    master:
      hosts:
        k3s-master-0:
          ansible_host: 192.168.10.81
          ansible_user: falk
    worker:
      hosts:
        k3s-worker-0:
          ansible_host: 192.168.10.91
          ansible_user: falk
        k3s-worker-1:
          ansible_host: 192.168.10.92
          ansible_user: falk