---
kubernetes:
  children:
    master:
      hosts:
        master:
          ansible_host: 192.168.10.81
    worker:
      hosts:
        worker:
          ansible_host: 192.168.10.91
        worker:
          ansible_host: 192.168.10.92
