kubernetes:
  children:
    master:
      hosts:
        k3s-master-0:
          ansible_host: 192.168.10.81
          ansible_user: falk
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        k3s-master-1:
          ansible_host: 192.168.10.82
          ansible_user: falk
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        k3s-master-2:
          ansible_host: 192.168.10.83
          ansible_user: falk
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    worker:
      hosts:
        k3s-worker-0:
          ansible_host: 192.168.10.91
          ansible_user: falk
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        k3s-worker-1:
          ansible_host: 192.168.10.92
          ansible_user: falk
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519
        k3s-worker-2:
          ansible_host: 192.168.10.93
          ansible_user: falk
          ansible_ssh_private_key_file: ~/.ssh/id_ed25519