all:
  children:
    dns:
      hosts:
        dnsserver:
          ansible_host: 192.168.178.254
          ansible_user: ubuntu
          ansible_become_pass: ubuntu
          ansible_ssh_private_key_file: ~/.ssh/id_rsa
    kubernetes:
      children:   
        master:
          hosts:
            k3s-master-0:
              ansible_host: 192.168.178.81
              ansible_user: ubuntu
              ansible_become_pass: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
        worker:
          hosts:
            k3s-worker-0:
              ansible_host: 192.168.178.91
              ansible_user: ubuntu
              ansible_become_pass: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
            k3s-worker-1:
              ansible_host: 192.168.178.92
              ansible_user: ubuntu
              ansible_become_pass: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/id_rsa
            k3s-worker-2:
              ansible_host: 192.168.178.93
              ansible_user: ubuntu
              ansible_become_pass: ubuntu
              ansible_ssh_private_key_file: ~/.ssh/id_rsa