kubernetes:
  children:
    master:
      hosts:
        k3s-master-0:
          ansible_host: 192.168.10.81
          ansible_user: fedora
          ansible_become_pass: fedora
          #ansible_ssh_private_key_file: ~/.ssh/id_ecdsa
    worker:
      hosts:
        k3s-worker-0:
          ansible_host: 192.168.10.91
          ansible_user: fedora
          ansible_become_pass: fedora
          ansible_ssh_private_key_file: ~/.ssh/id_ecdsa
        k3s-worker-1:
          ansible_host: 192.168.10.92
          ansible_user: fedora
          ansible_become_pass: fedora
          ansible_ssh_private_key_file: ~/.ssh/id_ecdsa