---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: home-automation
resources:
  - ./secret.sops.yaml
  - ./helmrelease.yaml
