# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:S3H0RqGXZ9cSkTdbi0s1xrBnzffhx4p+oUS5ZMpXdPAjPmiSmQ==,iv:2hBzaALuga+4UgwpLNu58K1apXDWRx4iIaGKpYQRPgY=,tag:Ea1sp+3uj3psOyXr8zwBCw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZFN5ajN4cTRabHZCRU5N
            K092VXNlMGE3Nzl2WTZOM0tqRnNEMyt3UkZvCnVtdlhDZmpsM2hwYWNyOGgwZzhU
            U29KbGdNamZndktKRnc2a05jREZQQW8KLS0tIEV0Zm84cjRLOHBsT09BeCtkM3NP
            blNlWSt6eFR6RDR6YnoxMlhPYUN4aDgKk2KSqpV7V9LJ8/8ettrWW5uZaMQdUu+8
            RBA0rqoA5TcIUGukKXrDwU7K0W0FBv8ha+JZWyjE0NQ9brrNnTBsPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-25T06:08:05Z"
    mac: ENC[AES256_GCM,data:/+miM71+STKnMaGZ7DKI4fdgwonS+EVjyroQtXoOOaLjNudInaRx5nRDYxlRywLqjk3sR21/t/9wrxkfvSTp6bYd8rLCw7OtGNblg6xj1sraFZ02fAEtLAne6SbF90ykFInmKYUABiCKGYqitBlZ1aeEV7M3Cllhj8sVEL1LhAU=,iv:8DkL08+VW2/uAAVvZX7eRlBzd1JuLfUDOog+5O/STEM=,tag:d7pbv3Jtv9dcSc4Da3kypA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
