---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: external-dns
      version: 1.8.0
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    interval: 5m
    logLevel: debug
    sources:
    - ingress
    provider: rfc2136
    rfc2136:
      host: "${INTERNAL_DNS_IP}"
      port: 53
      zone: k3s.home.lan
      tsigAxfr : ""      
    policy: sync
    txtPrefix: "external-dns-"
    txt-owner-id: k3s
    domainFilters:
    - "${DOMAIN_INTERNAL}"
    crd:
      create: false
      apiversion: externaldns.k8s.io/v1alpha1
      kind: DNSEndpoint   
    resources:
      requests:
        memory: 100Mi
        cpu: 25m
      limits:
        memory: 250Mi
