# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:1CsiCrTjC/qMCh4kARxRnJLNZPw44g==,iv:zKpQKuQat1Buax/N3iJFsmc20YViv5CD0QB3qnHdgFU=,tag:j4XA31ss+SfyWe/ci1TmfA==,type:str]
    api-key: ENC[AES256_GCM,data:4YjhBLBcpwWnraVu4VnEDoEsLrtEC4CGxYx4WZbIyJPFbi2wJA==,iv:pL3PbHrd/h3VcLcQhBJ8R8GcHIjG0yV+YMDkSpOXfEw=,tag:Nwypt/NepxUZpaMscUxH1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaExGTG5zR2R4YVVDWWxB
            YlNCZFp6Z0NkeitGLzdZOHo1S0R6OU9ROEc4ClhrNktlcVNHUU9WZEtNQnI4bExC
            VnNhbGRrVkJjajVLekxxK2xyd0g4Rk0KLS0tIHoyMCtNejN5MHBRUzhJZzJZVEJu
            bWFCZFNhYVZkWU1UekduNWdxMXRXOWcK+WAc2TlBAaeUaHV2GUUscmWNzkrNJe2v
            r++EpffinWp5mxgvDUqSa46e9jxqPpiEIjesn6cSbDJQwFcahsYkwQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-14T06:17:54Z"
    mac: ENC[AES256_GCM,data:BckTzOqjEzGxf6+c7bhTdPhxq8Lp2GoduhpaNFZRSbPPFpH0ORnitO7qdMHLKJNofkPSgw7F82aHX6oY6r4A+xbEk5zCKymAaG0G2RpJ2TddA9gLAz7+z5j3+5o7DjhMgpKfQT7Ov1mftRG5cfuoQmHhtFSjDAQhZkm4+24RI+0=,iv:UYwgJ4ICTdBOte8tEiT5BmTfq5Tnt0E2TXzBDu+Gqko=,tag:bagYzxsioxoJJVwv8N+S+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
