# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hA2kBlm5RSvSzNcKUdHT/Q==,iv:9wvTzShk+XLQgvz923jl4HnSPC4WOgyOyl5Orzmc8IU=,tag:PX1nK+6FFbiC7FHD/Hm/MQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:hhlEBwEe0FI7OnfMQxn2tovpIH9XJw==,iv:8DaZgQY+7DnwuvKKtoJ4airg5AL/3aMKXmkGsJCIyIs=,tag:TlLYXVVT1fYM8oCkaxMgMA==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:lC/VX8asLORTOfOsqkQ4FhLuuIDEEz54tjid614G7C4xRYel8Uey0aXSpqfVNnZIKv8RB1Fwe9EPmrt5JaX3mA==,iv:srDwT1UU7gmbA1rehczb1sNjYxCslhT3rU2BaeQlrU4=,tag:7FdqVWrGN/1R7dnGhFC4sQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:SvkNuH07H93o,iv:GdabHgr8OxMKzP0Qmu3qtdWwVyL3PTxbbQ56KX6An4g=,tag:wIh24lcbqyzERNsNcGmU+Q==,type:str]
    SECRET_SENDGRID_API_KEY: ENC[AES256_GCM,data:QBfafh5i6zQhqBEZ3u283CN44rvnfSvEJvHETLSHQzdH9hhW/i8hIaqARJNR7DpJvCPMQif1NTa5HtPCvsU4eNW6ex2T,iv:rVk1rGnSBIkn4zyGds3UOFWq2Axtq2iVft9seWVYIdw=,tag:DCkauRrW8s39yMhORk6jvg==,type:str]
    SECRET_BITWARDEN_EMAIL: ENC[AES256_GCM,data:0OHDZg+TCTxCx8/2PzezAsY41vccmw==,iv:N+H/9vvJ7hHHh/ELvwHElDywzz9XUzaH7+rcLHQv3/4=,tag:3oNcx1AskVPB4J7d5cHbQA==,type:str]
    SECRET_BITWARDEN_EMAIL_PASSWORD: ENC[AES256_GCM,data:jPcs1JLVcwBr6MMRm4AZDQ==,iv:APY/CbojqRSE1pMMi0snAp0OKwCN/Lzb/GgMvN/7WMY=,tag:7Xohmen0QxsvBKjjv03/kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-13T09:44:12Z"
    mac: ENC[AES256_GCM,data:UQF7AT4nG8qSovmN+QRJjdeIPOvZm5wspGvLj7gbIYz5FDkXn/4LZvV52xBB9yil5TLSiJCC7wJ+Ea6o8cLt9zh60ylYZzkY5nmi1/HiyyFWZbNX8QTkXzchr2yNppO0o61unvoZGipg3v2+ZjL98ZlRypNzr/EQrFfbfMgdUAs=,iv:inTU7Qhq8mSR4iVODj0/g7n9cCv2/ZPPWAC0uacxr/Q=,tag:clNPgjLJbWq3dm1vocy9oQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
