# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hA2kBlm5RSvSzNcKUdHT/Q==,iv:9wvTzShk+XLQgvz923jl4HnSPC4WOgyOyl5Orzmc8IU=,tag:PX1nK+6FFbiC7FHD/Hm/MQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:hhlEBwEe0FI7OnfMQxn2tovpIH9XJw==,iv:8DaZgQY+7DnwuvKKtoJ4airg5AL/3aMKXmkGsJCIyIs=,tag:TlLYXVVT1fYM8oCkaxMgMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-14T06:17:54Z"
    mac: ENC[AES256_GCM,data:c3fI/9TwGQFpIOCpdz2wkG/SdTFNkB+Wrngh/0J7ANR7eBFZ6+ga+rTnL118p9jUS6VGwBD+Marq/LbeCosl6tKT/yQgbNJ/ivmpueB0n7Uuo+glt9+8WnQ/lhSAKx3AS0qBLXpaMza7o3s2d/Y1KePru59/obNdmo4pql61hDY=,iv:Baq1L/dqkXBCaqHx+H0OCXe/CVfAHD3EOm/Wnjfp4F8=,tag:NYtZ0pm3Z5OHo0PIJTiRlQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
