# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:hA2kBlm5RSvSzNcKUdHT/Q==,iv:9wvTzShk+XLQgvz923jl4HnSPC4WOgyOyl5Orzmc8IU=,tag:PX1nK+6FFbiC7FHD/Hm/MQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:hhlEBwEe0FI7OnfMQxn2tovpIH9XJw==,iv:8DaZgQY+7DnwuvKKtoJ4airg5AL/3aMKXmkGsJCIyIs=,tag:TlLYXVVT1fYM8oCkaxMgMA==,type:str]
    SECRET_VAULTWARDEN_ADMIN_TOKEN: ENC[AES256_GCM,data:lC/VX8asLORTOfOsqkQ4FhLuuIDEEz54tjid614G7C4xRYel8Uey0aXSpqfVNnZIKv8RB1Fwe9EPmrt5JaX3mA==,iv:srDwT1UU7gmbA1rehczb1sNjYxCslhT3rU2BaeQlrU4=,tag:7FdqVWrGN/1R7dnGhFC4sQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:SvkNuH07H93o,iv:GdabHgr8OxMKzP0Qmu3qtdWwVyL3PTxbbQ56KX6An4g=,tag:wIh24lcbqyzERNsNcGmU+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhS3l2c2d1RzlpYnlmN213
            ZlZvSEFrWlNxQ2x1QnI2Szc0bTF0eHhmTDFZClJ0VlJnY3ZiMzFMRlI3T1luVXB0
            SVVKbGg3RFdCMFA1enJrQ3ViTHp4KzgKLS0tIDZnWmFOcjZlT3pVdStvMTViOG9F
            T3dPSGE1azZsTEJNUSsxalk4WW13V0UK868x/+KgqWxzXUu5tuu8IgivTjybMEMP
            rtBxzyKT07gUblCUHtUNJlwdCfzVc4grKrDOG7xq04KTLMFaSpe8hQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-08-20T08:10:28Z"
    mac: ENC[AES256_GCM,data:8bBlU39YR+Sa+Ua2l2ABc0KVYpod0xy6sXJxcf4HLtcG4DhrfRXmyRB4pvPkFXqMpd1PiExyZVry0aDZKoAz9TPs3vBXCt1+EOlMAbbhBJtzfB9NTt2TjWwg5UaEI5KEYXEQRXT5HRutN2707N0JQ+UYywzWvxk6IXqD1DPCwJY=,iv:DhzUJRAx3Y8JfLiBMTZEyrZ2970W9k0b2C4sAc+CWBA=,tag:L2MozIVMXQ2trDuYiNKibA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
