apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:yM80qpIm5okHvz3rpNCp9DJXO0OqXQ==,iv:/4+EidgBybWyHKnwltdiPJwXow1ESXxKvJTxDxM6Tj0=,tag:ZWhmphMJy7CMiqWuwV7G1Q==,type:str]
    api-key: ENC[AES256_GCM,data:pSZgAR3mVU57TxP4aoB4s7bJGyng4iRO6xj50hwxMn0Gsx3VvQ==,iv:hBlZbK1FZhZp0PsBYIINDFTHL6n/auyjXYRmSKiy/cw=,tag:Mjeh5jG+006WMRfgbxujPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEL3QzeTNTb1RnNmYwTkhx
            QnYvb0dic1hmRkhncVltU1A2RlhJWFBuTUhnCk1nVUxPK2tRREpwNzcxMVZlWHdv
            TmFVMXdlQVhXYXBJaUJRVFpJTWxNZlkKLS0tIGt3WTMway9DTmtrNjMvaXFLbmlK
            MW9wMm9MdHYvUGFXdDgxNDhYYzQxWEUKgZ8D70pW9TMBHVJ3lVdPVEw4S/AglXa2
            yP82tZ9PEjJRtfAisEhB0+yGsaXXVhCxbjhnqiJPfplcFWcFLNYV7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T05:55:21Z"
    mac: ENC[AES256_GCM,data:S99o4US7At4NEfVJQGytdZG0RT9QSu4/Wx3LnP6Tmu6uNDrtcYK7PIAdrOFOfKBHAU1fQrAMn18KqRafJZVveICc5ms9QHDlpVhV1izn25xqKLQacU3NSE+jms0h9g96AjBbJnmCHz69uDJ5I3+5RMKcmRa6c4z6ot3iWAxb/0M=,iv:eOB/Wlq4VtS0Uwv4d91eXFCtwWQp2HeUwSoxVFIb9AY=,tag:2Slc9++XLOgsAiHvoLhV3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
