---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt
  namespace: home-automation
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    fullnameOverride: *app
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.30.2
    env:
      TZ: "${TIMEZONE}"
      ZIGBEE2MQTT_DATA: /data
    service:
      main:
        ports:
          http:
            port: &port 8080
          metrics:
            enabled: true
            port: 80
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          auth.home.arpa/enabled: "true"
          hajimari.io/icon: mdi:zigbee
        hosts:
          - host: &host "zigbee.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    securityContext:
      privileged: true
    persistence:
      config:
        enabled: true
        type: nfs
        server: 192.168.10.10
        path: /mnt/Volume1/k3s/
        subPath: homeautomation/zigbee/config
        mountPath: /data
        accessMode: ReadWriteMany
        size: 1Gi
        retain: true
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
        hostPathType: CharDevice
    nodeSelector:
      feature.node.kubernetes.io/custom-zigbee: "true"
    resources:
      requests:
        memory: 100Mi
        cpu: 100m
      limits:
        memory: 700Mi
