---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: home-automation
resources:
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
patchesStrategicMerge:
  - ./patches/env.yaml
  - ./patches/exporter.yaml
