---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: godaddy-webhook
  namespace: cert-manager
chart:
    git: git@github.com:snowdrop/godaddy-webhook.git
    ref: master
    path: deploy/godaddy-webhook
  
