---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: godaddy-webhook
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://metallb.github.io/metallb
      chart: godaddy-webhook
      version: 0.11.0
      sourceRef:
        kind: HelmRepository
        name: godaddy-webhook-charts
        namespace: flux-system
