---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: godaddy-webhook-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/snowdrop/godaddy-webhook.git
  ref:
    branch: master 
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: godaddy-webhook
  namespace: cert-manager
spec:
  interval: 10m
  chart:
    spec:
       # The path of the chart relative to the repository root
      chart: ./deploy/godaddy-webhook/
      # The reference to the GitRepository
      sourceRef:
         kind: GitRepository
         name: godaddy-webhook-source
         namespace: flux-system

