apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:IYtov/xP+idJD+3K5xlPslPNwUi/7iNwp20RmHnQtaUDu+JmIQ==,iv:ozsGTOoXQtbI/PW/6Lv0rPirdUndA6dCvXLYbRXfy+0=,tag:j/yhh0xQR0zWE1YDMCLPlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNHpEUm9IdlEyNDBrYzNk
            RU1OMzRUK1ZyNEZVM0g5QU9ES2VXQkdKWlhJCmRreDM2aENEZ0tJNTlwSjBucm5w
            dVVNQzZYeFhJOXc4ek1UWHlFUlYwNUEKLS0tIDZHZEdYa3ZhTGxhL0FkU1J5WmpB
            WHFDWC9YRElDQ0tDOGwvelYvNjlGRkkKueuloLe6vp/ak/uS8fiIeu91/TMO20Ae
            96Ot79i1La35mDZJHf7NkHYofvHWYE5u+vQkwsm0C4RLspoy39liAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T09:50:13Z"
    mac: ENC[AES256_GCM,data:9ui05AmGYosvsTezdzNT6C0r//luzHQ8D2IuWWpFSRiDU+8W+tPF9LO/wm3BNYbP9m5yP6P2RpoyvS3a+XFZ6zZwjfCYgY3S6TRHIWzAs6N6k9iorb3yDN2L9KA4061PLCbgE8/vUIREYDO7JlLoo/hEb7yS2C6zi2wEjbsASTY=,iv:qWUnI/rS1TKYPmW4KCNLAUZ8GDo9TsV42x9GxMG6hew=,tag:RDkxznXzA8qMUthJu0t7QA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
