apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:t05wasd2VZ9muP+azsZ7WEXLBSXXdxjJL30EvLAczW9AwHrgDQ==,iv:25ZVy76Mu7VXGGa3hnEfcBF0yLz7tAJaT8MTvaljkX8=,tag:uzuuJjxlUOaoik3oDdIcUg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsQ0EvKzVpaXNOVktoR0do
            RTF5K3NacmJDSmdIUjJXTEdFZVdNQkRRUlFRCmRCMlBIUzQzbWVrRUJMR053Vmk2
            RWlCSW0vRzd3UTJmNlk0Q1U0dTk1SzQKLS0tIFNvVGRKdW9nVHZGSk4wa3kvMTUw
            ZXg5cDRVdE1qcDJqbURVRXY4UVU1MFkK3/c/CPlbnxV8X8jTuaRgSiM6U8jVW/6m
            Ker+nPPtDbpeEV289HZS7eEVBn8kMvji8S39h1HZC7tknQcDRA8fhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-25T07:23:45Z"
    mac: ENC[AES256_GCM,data:amui5mSiPHJsPdG1A3tjgLRJsqqNaLFaCS2msHN0uvt9CRkWlwOxBAmHquG8MIZQd/Cf8o+byHIaoHHZsw5g+rdE30H17RuXvOQ/wcGmjpKSrmDkg/m6XpjLZ7u5qeoG/M++q/3xapCimYomPmMx6EYJBkNibgkW1S4hiX0UA9M=,iv:1VFCFjnm7bxbYGrUJ2tl6CsY/jzIZ7Ta/qyAoQSRv0k=,tag:tLhOQDqV0bHPQFGPQSlEHQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
