apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:GEJrOgnK2YET8iVUdVxLx7q4Ud/HVkJD1SoF1sDvWjsqhh2aVg==,iv:34k2DZC8vgD/hd2UqaA+Lo07H9acLFt9/rUMGimY1is=,tag:Vh0hArDsuo8KhtipUPXYmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEM0gzTW1VWGYydkpxVjRi
            MngyOFpMVEh2NUhtYWQ2M2xPbEU4M1Q3b1J3Cm1UOGtMOCtGWGY2Z0R4N2VNZ0pm
            RVhMS3R1Rmd5RTBaZTZkUmJvc2E5anMKLS0tIExaU0E1U1Z0M0wycklYMW85cGc3
            bGt0QTRYYThiNnkycUF4QXpkRXptdlEK33y9YRAzR0LooYSLgHs6ID8NGWuqhwzV
            0socU4t4hC2FAjUIiL64YjrvktBI62Q2HSQEIoqlC0ePcERvt8pjDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T16:13:35Z"
    mac: ENC[AES256_GCM,data:LC6Esy1fGtsGf3TFFs9u+hdPTnKCZeN3ca8g6HpnEx5MUwrbAqXgOelHsJ1E+IFgfks2WvqkZH2TUWlXKS2Xy3hXy31qDPkMw8+6i+qXT8hca4GvB6+up0HtnBFgeTpo5lsyFACzwYi/hvlIhZ449+7NISMskPDNNaRnn6q34A0=,iv:ISBtUYVgTWThRPJxRRJCRF+IG9nKXv81hjnBoE9zNGs=,tag:ZTjXoCbjsqdWS7pmUspkqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
