apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Qb106a3eVL0QPgb0BTjDbfqlgtmwXZIVcQiCcyEIj0ya3tmkOg==,iv:FniJdxNxu7TyNt6Y3KoIG/EpwwJu3MWfkoc2EWsfgXg=,tag:s91mDAL1da7Eegf2bVtnzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLaGQvVUJqd0hiVGVwRC9r
            Nnh4czE0QXhLYXlvUTVuVVNvM0VWR2ZFTENFCmhVcVgyTDlIcUMwN3NHaGJYU210
            M2tQMENVakhOdlpLTGhQZnh1cjV4NnMKLS0tIDZFMG9yNUk5dE5jMmg0WE1uN3hq
            NllxY24yeUQ1VlBGamhzcHRmZ0VBaE0KTDLpF11ccJGz1hIlT6rdOm2rszZ+qGcQ
            o68uq15+in/9lwIA58NzYJQVanuImDM9IZrM+Mq4+R7Jzix74k3oNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-22T06:56:09Z"
    mac: ENC[AES256_GCM,data:coMwq2CZ4GXlAATzI8mhzoAznQSviAi5plpuSA+Jc3IV2m7o+Q/lPu5piHHfEFRB1oY3BhqxIH4v7tYWtb2PNI1WjmyvRqxrboyhVZLORheEPfJjQpciKXKBkKCu/n3/8AiXIJsFv28S8j3YohfuQIoi1trNpi91PGVLY6Fgz0I=,iv:YwYaF5HhsNe7OcxzbOI9PdN0eAXgXAY4/MJOJli32f8=,tag:MpxKnQa/Pr0uK8t4mZ0Fxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
