apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:HmDCqJp5lDwcFKtCn9GEUONzHp++hw==,iv:TVSyTJVCdYdZlRc6a8+XrDAASTqGBCelP7PadqJubQw=,tag:NL74PR+RvuMFf23aYyWAcA==,type:str]
    api-key: ENC[AES256_GCM,data:uST9RVKDifL6r9KWAKV9QB9Gtku022uMugLk8mdF0kfMZkzGvA==,iv:tYkAPBRDjFCIrnW0g5bR6AreBipt6lLe57TLMZ+ZSGs=,tag:YSFwQ7IVnmExBtBpEaxTlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBteUs3UDlnQUtRMFZ3dThT
            RGRqUHRTN2c4UzFUQlgrYkluSk5yN0J6YURvCktHQ2xqRVVVd1krSWNYOU9abFcy
            M3NsT3Q0ekNqcnZ1Sk9uLy8wUDhSZmcKLS0tIE1wMlY3Uld0amloNkxwaUo4QlI4
            bkRnVksycEZIVkNOYWFqZVB2cVdlMXMK/z585lVf+PC17F8ZPCLxsbZ8CDIGn7ty
            P/W45r1f+H4VDrormzsbcG2Iw0i6SiXkb/cFs9dG/sy4/EMIXKRMFA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T15:39:27Z"
    mac: ENC[AES256_GCM,data:TVveLIFjdZN5luXEMCjhFxxmutBdGlmmMA8XCeLESgdYUsP1SYANLe7xri59mPVUM2OtGLIJam0FsUuYrcLYmpBGeI4/eS8oOZT2rQEJFmlWbw2jotZm+ovefUIOzmjVoPGELUoQJQyEImra8EQ54OwQ3JIpD77bsivw++FEB64=,iv:bHcmBdOImof/yp5J0qItHrBOp8Dkxh3mWoTuBo6ua54=,tag:IFWD34hcEIVPEgHMZ6+wXA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
