apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:BGLAV/uN4k4isOmZpWKoAm6Qo/fFFA==,iv:DIAaFbPnOlfY/Yk7gn62oCdrFEPEbtD6L0TRZZ8zRWQ=,tag:I+ltuw4lh3NGl6zJ5cArtw==,type:str]
    api-key: ENC[AES256_GCM,data:J8ZQ48pl5K4AL90cmr7s7Oz3xxNMhGam5N4me48goFkoveZREg==,iv:cHVS2Duz7vXDsWtZppUWf18lEaoYhbAJvyAPQsOQFPY=,tag:xSbjLYeG5zb6M8WO3xdpEA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTWttL3ZPZzgzbEJVR2FS
            eW9PSW1BRW1zd0pvZ1R3Z1c0eGw0Q0RLOUdvCjdrOW0yakMxYlRDcEpqK0xRWG9X
            U0xOODl6WC9QZVVIdHM3dDd1V2RsYjAKLS0tIFdOaURIMkIxSS9pMmExbjJoVGcv
            Z2c2dkRPdFhEZTZFeGhnUHdvSVF5UVEK9Ha/28rk6m/Nc8szBC4hY4UtNhhrF0lx
            5/I4SwZvhQxgl8eCMi8FGbaLWzPzvscf76xYjYlmLxbmk45hfExDeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-10T09:50:13Z"
    mac: ENC[AES256_GCM,data:kM2cAqVU/i6EPszzHXIbRlG9UP58GBDkovEoU7bxXJPXey495QVZCVsuvscyUrcLiCmRr7ongSnQ/y+94WOHL8MCoMlYQLS07jWVBFuMtiObFWjwERr5O5mw+z1QeSjomtlrk3IwYnKxr71/z0v7CpjklkwNV6TpBzQrx0aSP+E=,iv:GWHmm9ipvINb9gqeCa5fGBvZaH2lx50dbK1BB5GveXQ=,tag:4XK8VVJR8QNAV/i62ZGmmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
