apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:42yfL8fqJOqQcSGamf7AoTYrbSeFEQ==,iv:nN5q5H3aBsUFer9negbiZx6KxyFjvzi1DZrhHCYvJ9U=,tag:zpGh4Xw2wyxmEoeAn8TJCg==,type:str]
    api-key: ENC[AES256_GCM,data:nalW7WwVRdnEcW8DpQh0mdSujM5i05pf1zlzUaOxQzTOqldtVQ==,iv:L5rRxvqZmT6UAdADqSPFVXTZJBuV9CiXeeXZvGw9FPU=,tag:QxWFuuaWazLLJdd6dTYyIQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNUpacUdrdDRwRGl2N1JD
            SUJNSjQwczFYZnN0b3AvK2Mwam5xN1NTTzFBCnZBZ0hJR2F4TUxOTHVrekhrRE1X
            dlJjdDY3Ri82V0lHaWRuTFFHZ3llMjQKLS0tIHhtQTNqenJ6T3RqYW1BcnpuemtY
            Qnk1L29aelJWdkR6eDJlVU04V3VDWXcKfTrbOirxPSnsPnrOcz6FHZjvErsO+VHR
            /g6jDKlWHXdH/PeWN6jd0gRbA6+lwu/woibYtaz/Mg3fEOYFqG4TXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-19T16:04:30Z"
    mac: ENC[AES256_GCM,data:S58PKA1dyUDA4oMArF8g0lif8M53WXamcoQ4NIOqGRhss+9ijgTcIF/T0P9af19rBVCX1U6H66xv4+99hvU0bxipze1tnGepEHmT/9WtsPIABZ2vJH+hTHrr6tsJW06NNVNSBVNkTBa7560B57hKm6yZ33HQ4rz+AobFi5eig08=,iv:+ON9vAiP7YMJW/yhrQnZOZWnKidcrEaNbmuoOQwxuqI=,tag:wZJv171NyHB8fACueZq6Cg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
