# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: falkssercet
    SECRET_CLOUDFLARE_EMAIL: emailsecret
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7dulnc9q3dsr6dfqgfec2mfufc0zckrntzqkfx8rvhzj9prfajq8jmztu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnRVVwN1JjaWVCak1TN2JU
            Wks1R3QrSU9qUEdvMlVZeksvMnR4TTNFMFZrCnc3QTY0YzVEaWRJQncwTTdDaC82
            MENtcVRmTFVJMGtRVGJFR0tVMzRkZWcKLS0tIEcxTFJWenpJNWVYaXVrcFZPSHZk
            eGZpU05JVElGRm1XVUxKTFlnVHVpcHMKxyXGLAMN2Wo05aaYfPfc1LVxJ8et4XXM
            DFi6Zv65ygY7d2qzcm4t+LAOXKsBJc7dkGzz2a80jbHTE6u71GKWrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-18T07:04:21Z"
    mac: ENC[AES256_GCM,data:CLsoQPZfGD22/IXyauOxCmV10S/RksOldewa4KhS6tgSjEPPc1vrdukIfO5O3eESpLhCSYNPyE1vn4m6v+ngdZmpcd1fBDdgl6bda6ei3uJsIRrm7DLZL5MD/D/mJIeXIfI6iy5ty4UBWd56SeHakQB3A73QYbNC9Oh7WtQMq84=,iv:5J87mSnMNt8T3h3N9ozRVlxywN3HkcHpDx20l2bFgNc=,tag:8GGnhhAu1sF4Zz78cFx6wQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
