# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:tAbDklCnzo494KPHqeTj9w==,iv:w5Mndbn9xzlE6XBeYAgIo2LFzHKbRYnz/37DMt1yyNo=,tag:0PLMjXVyK7me4eXAxJZaKA==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:D59DEzq1oZI=,iv:wnZ4rfputTElyWJHJzoE46prXTf9JWnRTQI23HRGqvw=,tag:v2x5HrFoxTPlNu7tpAMzbA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:UfEuZ+Rs1rSvikT+ZdMe9WkFvFzLVg==,iv:99zR7nIya+glg71W8vWQOLUeJSasoBYAYlKnJ1WNp9o=,tag:2ITd0y6HZIxw90tbPR316Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArZmxpcjZCa3Z5aVloQzdS
            M1JHNFF1cVBrdXY2M3REOHhlL0dMWU51LzJnCnNNVTVtdUNudGs4dE5COGtvb0o1
            aThlL1JqMFVHUGRNSnUxV29Zc21MSmcKLS0tIDY5SXRFYUwxNURFWFRtZWJVY2NN
            VG9kTWhaV2pndmIrcHVLTlUyd1N0dDAKL2HLkdNoj7iHftQJ/nqt5lb7G6Q7Rlwg
            r7bDh6trzY6R7xTpkGijkO7y+MKshxSFZ0kMddAWxTqF01YxZSw9Aw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-27T05:41:31Z"
    mac: ENC[AES256_GCM,data:lDchXuvLQCV5Bmzlj/IIyVcgdC/nV25MCdXjMX0p78Hhy+Ju/wDgyNhpIdJuDe41MSJFQY49RGMC0NX5r6m4vQeJPedD8Dcil4McVfesVmtCGjv/VN8pkDwYQzUZeTFeYGoPYxOKvf8vG5n9N6ExycbCmbfvFdxDjJilcQwiAu8=,iv:pBmONLuFxzyB9DaDKzgV8UG8beNA+AKZAQiqF0x8Mcs=,tag:/dswIeiwmk/KZJUrZ9sK2g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1