---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  DOMAIN_INTERNAL: k3s.home.lan
  NAS_IP: 192.168.10.10
  INTERNAL_DNS_IP: 192.168.10.7
  METALLB_LB_RANGE: 192.168.10.200-192.168.10.230
  METALLB_TRAEFIK_ADDR: 192.168.10.200
  LB_PAPERLESS_IP: 192.168.10.201

