# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: winkler-home.net
    SECRET_CLOUDFLARE_EMAIL: fwinkler0573@gmail.com

