---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: democratic-csi
      version: 0.13.7
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
      interval: 5m
  values:
    csiDriver:
      name: "nfs"
    storageClasses:
    - name: nfs
      defaultClass: false
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      allowVolumeExpansion: true
      parameters:
        fsType: nfs
        detachedVolumesFromSnapshots: "false"
      mountOptions:
      - noatime
      - nfsvers=3
      secrets:
        provisioner-secret:
        controller-publish-secret:
        node-stage-secret:
        node-publish-secret:
        controller-expand-secret:
    volumeSnapshotClasses:
    - name: nfs
      parameters:
        detachedSnapshots: "true"
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          protocol: http
          host: ${LOCAL_LAN_TRUENAS}
          port: 80
          apiKey: 1-as4zedTj2DPSNmoWrXmVSRtiYkbdSSLoxTtyyP4zDZW6BbWkPuPeWBBS9DPNDhlt
          allowInsecure: true
          apiVersion: 2
        zfs:
          datasetParentName: Volume1/k3s/nfs/v
          detachedSnapshotsDatasetParentName: Volume1/k3s/nfs/s
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
        nfs:
          shareHost: ${LOCAL_LAN_TRUENAS}
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
