apiVersion: v1
kind: Secret
metadata:
    name: csi-nfs-secret
    namespace: kube-system
stringData:
    api-key: ENC[AES256_GCM,data:Z5RCW3ZACSMVF0Go26z0Ha2UvoMnSJ3exnaGPzueHsDCgF1Gwm7jJ7eYfDjkurKFRLvF3vOI2QFCZ4Qqunt8KRKm,iv:Pkpplnii3YlKIsZ8iQH3Vy2gQFSdStlGC7ItlrnOKsU=,tag:P++oqSJ6f4Kk3da3dK0IGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTWttL3ZPZzgzbEJVR2FS
            eW9PSW1BRW1zd0pvZ1R3Z1c0eGw0Q0RLOUdvCjdrOW0yakMxYlRDcEpqK0xRWG9X
            U0xOODl6WC9QZVVIdHM3dDd1V2RsYjAKLS0tIFdOaURIMkIxSS9pMmExbjJoVGcv
            Z2c2dkRPdFhEZTZFeGhnUHdvSVF5UVEK9Ha/28rk6m/Nc8szBC4hY4UtNhhrF0lx
            5/I4SwZvhQxgl8eCMi8FGbaLWzPzvscf76xYjYlmLxbmk45hfExDeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-05T03:32:33Z"
    mac: ENC[AES256_GCM,data:KjJMuS2hLG1siMvs7O73jBaxb4ij0fd++UCDoCrgM/uLt6v5ynbaCQeWBuQr/7Okaag8gh4soeP/WEoahHYgUHZs9nQ8RlXMqED1GCmq68LBYcMilgEgPcIELuW/v7rwdTUoi18cGtin8QRoJA65gSus6NE7U97Fv99PcdmiyMI=,iv:cZv96mB4f/h/E/4UWueCW8IboYBlKUPW4PjoTCsRtf0=,tag:Gw6md67R/e85X1v+LaUdfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
