---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scan-to-paperless
  namespace: document
spec:  
  selector:
    matchLabels:
      app: scan-to-paperless
  template:
    metadata:
      labels:
        app: scan-to-paperless
    spec:
      containers:
      - name: scan-to-paperless
        image: sbrunner/scan-to-paperless
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        volumeMounts:
          - mountPath: /destination
            name: consume
          - mountPath: /source
            name: scan
          - name: config-scan-to-paperless
            subPath: scan-to-paperless.yaml
            mountPath: "~/.config/scan-to-paperless.yaml"
            readOnly: true
        env:
          - name: PROGRESS
            value: "true"
      securityContext:
          runAsUser: 1500
          runAsGroup: 1500
      volumes:
      - name: config-scan-to-paperless
        configMap:
          name: config-scan-to-paperless
      - name: consume
        nfs:
          path: /mnt/Volume1/document/consume
          server: "${LOCAL_LAN_TRUENAS}"
      - name: scan
        nfs:
          path: /mnt/Volume1/document/scan
          server: "${LOCAL_LAN_TRUENAS}"