---

# ssh_authorized_keys: []

ubuntu:
  packages:
    - hdparm
    - htop
    - ipvsadm
    - lm-sensors
    - nano
    - nfs-common
    - nvme-cli
    - socat
    - python3-kubernetes
    - python3-yaml
    - lvm2
    - linux-modules-extra-{{ansible_kernel}}
