---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tika
  namespace: document
spec:
  releaseName: tika
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tika
      version: 2.2.1
      sourceRef:
        kind: HelmRepository
        name: tika-charts
        namespace: flux-system
      interval: 5m
  values:    
    env:
      USERMAP_UID: 1000
      USERMAP_GID: 1000
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "web"
          external-dns.alpha.kubernetes.io/hostname: "tika.${DOMAIN_INTERNAL}"
        hosts:
        - host: "tika.${DOMAIN_INTERNAL}"
          paths:
          - path: /
            pathType: Prefix
