---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tika
  namespace: document
spec:
  releaseName: tika
  interval: 5m
  chart:
    spec:
      chart: tika
      version: 2.2.1-full
      sourceRef:
        kind: HelmRepository
        name: tika
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    env:
      USERMAP_UID: 1000
      USERMAP_GID: 1000
    ingress:
      main:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "tika.${DOMAIN_INTERNAL}"
        hosts:
        - host: "tika.${DOMAIN_INTERNAL}"
          paths:
          - path: /
            pathType: Prefix
