apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus-ssd
  namespace: monitoring
  labels:
    app:  pv-prometheus-ssd
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: "${LOCAL_LAN_TRUENAS}"
    path: /mnt/SSD1/monitoring
