apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:p/diOME=,iv:sa1b25rDiE6p/vUrhKAfWLWupWc0irKII/6/vRn5DMg=,tag:OzjXROGvltkljgZn3DuuvQ==,type:str]
    password: ENC[AES256_GCM,data:oBNAHXPooIREowvO+ChwbfJ2bmrYN2Cvzrg1kfYyIaoT9HxYQ+EFXEV8yQ8+NgXj4uaw7BwFWVGV/0lT,iv:6iiaZKwfUc83xuQ8dmffrIdAsZCSaG1RjxmRgWtlJGU=,tag:tb6/8Xkd1aLJL8wIpKr6Hw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUVQrOHRlMzAvSm1xRFVE
            R0JxKzIvcFFIUHg1ZTRmZGVFTEFIdFhJVGxvCjhaY2N0NStqRFhPQnZyY3BKbkF4
            WW00a1lEaSs1V0V0U1JKWWJEOCtoRHMKLS0tIHZCUDlQajhsR2ZMVWIvSUdyVFMv
            Q2k1OWkycW9VVXVMYmxLWHFzRXdKMGMKDR4PSGN7ltLoUhR/erLxusOnZkqOB1io
            /TbwtSUVsiSFuFLezgr0SHOj1MIK4NPjJzBT+tEQrmn1IG+c8U4PjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-09T03:08:45Z"
    mac: ENC[AES256_GCM,data:i4GMOYbl83p1cYMVPoHavXK8ZWoJYt+13wbCqhyF3NpxKJv4aWGp3Vru8E5JiD+X+FycKR/MdJsmGiWCyYlLqQKjVkP6JDm4Z7ppJVcSVgtJGRcS273518IvRhX3J0qbSqc6afZJTpTXuK+wVLJ7PxoFOKia9HmQg2LiCHm6T7U=,iv:FX3JRRAwnzt0kKpLyaSo4Urqy7P99Fe7ZPvDbJmEdh4=,tag:Y9wAigCtVhvBfOptohkYsA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
