apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTWgrVDVsU2o2Z1hLNjNH
            ZnpMWmRYOWtNdHcwbU5Lc2w1eDc4RDFlNzNnCnZQS1VjRzJXUExCR0puZW9wYzZX
            ckZKU3B1TUV6MjBTdlZSS1NKNjFMLzQKLS0tIEptZEVQMzYwVzQybkE5dFhDK1p4
            OHNsNVJrd3hYZWZOWnNNWk8ydEJEbm8KJVRO8qA/Sq8Ok3ULnu6muOrX6A50CoA6
            ogEF92jfRZL2w7AJ2Wgdk44zkmvfFzO/J6MPGTwXRkpGaUxMASFChw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T15:39:27Z"
    mac: ENC[AES256_GCM,data:W9M2gf6CYKnH4EAVXAf4l4j1vMoevncgu6MZLEU8z93zY96CmKHSyZaCoZoVSnZA/0VRq4QZFKAswl6jchTJQDMXxGarXYkIhd2jhZ6G/kez6Q5VyfVvNzjDtthmX9JHV6s3hfa0XZrnrGdfuauvXanZZ69OGPQguHvAl8NMrOc=,iv:gtAqOyokFrAjs1HB7oaMLZ5KvaGj+e+amZJEOMBggiM=,tag:iZ3QMQrc1zwSWgKDAnV5Ng==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
