apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5ZzhqelJGbDM4SlVMdU1t
            MjFFaDJRSENWNHdCdGpMdWxuMlVGSDU3NUNJCjF6YXlYOUlhOU1mVnR4aEhXTHJn
            bGRDS3pBZGpLVnk3bXdFUFhnU0Z3dFEKLS0tIFFBM0dGWVQzN2ZlWUdjRCsyS3Mv
            Y1o0TzVqZmtreVBRNVV1aE40VkVvWkUK90BO6WRYEJbbze/PSQenp4C/uJ448RSg
            I/dNQMAIi425LYhTfsMzjvwGnHY5anMLZySmRpCkvHsMcVUtowBNNw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-17T19:43:19Z"
    mac: ENC[AES256_GCM,data:QDUxdJd6wcbN+WaUuoi0+A07djuuveZ3bHy1paQ4x7xGBu69N6yJckg5/Hrpxd4WLqg7o88vzv8RCCTEjPtI6xxRgi+kSVVditrcxY/smxabtzDW8fjkjVdtYa6blH2jumy9LnN69HTf20TPln1b+e8Xv82Re2HZyokUb5n0Dhw=,iv:02e26Iqw7PBg+vYJ4C7kAclAtGYc7qc8Uw9F/a5IQTA=,tag:bE1hZeBr+4mVCjJaOzvtOg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
