apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:PvnpZ3c7XadO4gAVf9YySIAfq9NMpRzjQ2Dov5vwjDxTgEGkO0I4nxui39g8WkkBCy6yYk/zLk8NXk4U,iv:a45zZL4iNj2sWtALMQX5JZAF7f1hUIKypVXNppo+bT0=,tag:dbqvfpCq3Pk+Bz11Nl4Erw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOVnJHSFAza2dzVG5yOG5L
            MVJmb1ExWjhsdHYzeEo5bENza2lhU2w0MWpzCnBNSEJ3K1BKTFNVRGEwdjlmYVha
            RC9vSi9idittY1VOWG1VQjBSOVRDdjQKLS0tIGZkTnVHSGxxYjd2OWw4QXorZnRt
            ZUVpWTVVbjlvVVpDaHRsR0M5Z1VxWk0KFNFo/s+uacG4Nebx9wVbh+Cd58QL96z5
            2nozb09zAoaSAQsVXTQwp3dW/bHaUMbaMfXU33z1WuvQP8FyOSYMsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-04T16:13:39Z"
    mac: ENC[AES256_GCM,data:OMiZIRr9HuEx9nXYBtSp8v1bFqdh6umZxPjyG7TmOB54Me9PXeVxk3F659+Z2oAlWzUej0/pfd8ZciNa4WewxfTHeF5SGvUbt157El1RmK7Y4IaRlsRRNbc5oQpeUB9XCwBC1zyF2wdMedgbYLU5SG6/esOfmj4Ure6/lD69I7w=,iv:pLwNsDXG6lZ8XhPRk0TSy6TUgxqgCiotKri2/DemJys=,tag:1e7wi8t7FWjIEMzlgmlPmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
