apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:SO4tUQnbAwhsyelwhBa372CYiJxWrBgXkZFQmFD4SPIb+6MUlimoFTopG2LOKv5T6085AOM4NA4u7NnP,iv:QNc1QmahfXzh9OLNcUr/3Xn+ewnej57Z3FpH70gBItY=,tag:5BeWRRymwZXGYpOCX9lMMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQkVJNU0xb05IUDVNSWdi
            bm5iK1RSWmNKNWQwQ2NrNktUUFV5ajZkeDBNCnp4R05Ld2U1c0hIREp5TnZKODdZ
            VFUvR0FjQ1JOb1g5VVdoZzAwVzEyMWMKLS0tIHM3U1J3Y2tXbUlOdXhxK2FaSkJ2
            OEp4TzlmMnNRU0tSVERNWHZNRjNvSjgKIcPaJFkrLakKerlqW/H5YjxFmsTFhmWI
            vy2c/McK+l31s0iAVy4Ixrf5UcJdSIxtLNEREd4CwK7a/q0BX0Gf9A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-01T05:55:27Z"
    mac: ENC[AES256_GCM,data:AYqJMp2YXX1rR7zVed5Qu7fPKq2eUJo0DxunSbfG4DuiYpEBrMi/+Wcciz/lyDvKxu+klvZmmyTf8Bjngyu0PXh5SihWV3UlvBgAASiNR2jw+7wjqBUYYsllxykS7Q+VdZrQ/6tS1fzCMTJv1hnJSSIH8/VcuBRfJOqiNt4so+M=,iv:AdIGxW9kn2UnC1fmIz19P4ACdU3SvUuwD29OF807avE=,tag:PvJ7xTs22UWCRhvq+hwfxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
