apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:mmz7LsQvf5tEInFV19wdeFscvklHiq0u34+NH9H6RU7z8dDVOow1m7HEfNmHHsNka801pEKubIAK+TXc,iv:Vy0fh0EkHYLNeWL6Zf9TSACHWKT2CfFZWkExdncf7Q4=,tag:x6I0LvPxTxLJxJJVydSA9Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNmF0d1lkVWlxQ1U3YjR0
            OUYrMTJnWitZMFpTUVhZeUgweVRWUWRSQXhzCmw0L2dNZHVqRzF2cXF0MXdLMTlQ
            dEswQlVsV3doaUFiV0JtSmtLUWhQaGcKLS0tIGpiZi9Ec004T1VubjA0b1dzODcr
            dnM5cnpla2RFYU9uTklOajFUODdNTDAK37t0i88mf3f2KEWBbpLUh8gAYgYXMXz/
            bJo6rvGD8cDyk0FV01sbJU0uMN1cJQXtTg5jPQxSfE5/NmWVANNBhA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-05T04:00:58Z"
    mac: ENC[AES256_GCM,data:Ldy+KEQNY7mMt04nwmki60r9AgRWSmh7RnRT1Nm/onLPgGTUzRUiMv7NkUnRPpDgYM4eTX1dbxf71o2kA5aYcYEw/9vrdidqfv9bhP8m1JauuZq1c4F6HWFWo5SGRpVNNDqnEK8UKooJaCaQEDMl7CIWkAY6RhRjkLjsnwLi1jM=,iv:IPm+qFTFZJUJ7gtzug87qNo11b2XFeCwGNTh9eOvcOw=,tag:g5rQNq0QYoH+8Oiw9bO9kQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
