apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlazRpdzh6NFBtTXBQN0RS
            Zkw1elNIZG4xSVUxRUlqc0JNaVFIcjEwWG5vCkZFUnhIRnp0Vm5iN3E5Q2FQWWVa
            M21RMk1XM2xWaEMzRmVxVzdmT2JOYUkKLS0tIE9WMEx3VGNhOXF2cVVSbWF5KzdP
            cmlzVUtjaXJQMWI4eU0xeXByVHlhRTAKBSoCTdqM9At+HD+9JA58NR6DeKTot2FG
            6pboN83WHHEBwQWHVBSEUVYwrej6ejIHlljgA45UpnyllyiKhheyGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T15:28:58Z"
    mac: ENC[AES256_GCM,data:g9DFOrXfBiSkdCOZVaLvAl1au6rhnuDE4O/Xn7OOi8CMdI41Zmb0UqNGfg7xRXT+YY1+chhF1QI0f05EQk1R000oLMMDovfrqBkxHEB4Bj/fKGS4+F4qytQQCN56s0vy0YE/e3mLG+ww8vQHD4u5fctXNfPrHld2kmN8cFGtMQw=,iv:X6knY6/6mP8jQ8TNR8b6L/FwXIlI/P/XGSHrPv2geYI=,tag:83bCMcZjONgjZInwTg4svw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
