apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhV3Y4RXhyVUl5eE9RNmY2
            bVQxamFkaXZNNGx4Y09tclZlTy8xUjFEOGp3CmhMYUFmL0wwcmdmejBKejN2cFVn
            MkxwQzZKY1ZpQ0x4SzgvVGxIcnhUZ2MKLS0tIHpldWNEVGhocFIyWTRRM3ZrZlhH
            SFJxVWF3OWUxMm9FN1ROK2J0QVk2Y3cK7wkJfShsdwCqZkXNW+TPLanDorgwf660
            z5qo5dDhr+UODDMNwhj3rq5Q9c8npLBgG0YghhNEoreFbsS8TmqjKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-15T15:21:42Z"
    mac: ENC[AES256_GCM,data:86Fblc5B+5/NLluAPE6c2exi1sDd5o6E1yAQdb1zXbECvPy7F6WEeMPTxihJYqitspFPB+oLaMOB2oy7HgUn3ZVGVKhnf6SxJ+7i56QBx69KKPbHf4Sf8KEdJsf3E3NXMxQPW6CmLUPfJjj0vhhrnQJMvZ9hyR/ogVwm16DuUQM=,iv:CJH9nNd4pIDZSXAalNufFW6X7YFCmEWOs+0+2kvqRbk=,tag:0dlLp53Pf+CXYLDUDyjdkQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
