apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRVjFtSGljdmg0aDFOVkNu
            SEhvUDh1cjVZOC9rdGxlYjc3eUkvOWV3VndVCnFzNGVyTmJpa243cHZiMHBxT2Qy
            RnNrZG5adUhOa0VQd054cU1XRi9CQk0KLS0tIENuakx2TlJDV2gzMzM4TWVBY0Rh
            cWNuK0NNellNQytqVWlYRlNhZ004YU0KBA5BmWr/qLBBApQ9qp6jOiE5dxEplPG9
            Q1oDpwq9JitA4QMOnXmrw/eaQBW/QdntxBjjt4Q7k6g+yIvpMSMEQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T05:39:11Z"
    mac: ENC[AES256_GCM,data:GMP+fUf0SCJJuLKM0tBacdkJiBvPSbexgRo0hnwPDj9fwG/d3O/Qk2+3MdZZ0Kd4MMYmb7vgM+EFMzlIUCVV2tb2m+mWKyZhMx6SmNJsS0BphHCYYBptI1Lbqy0ThGP9To1Xo9F5qVmPVOV7MP9cyTy85JTJDTEySRVXPcNQH8E=,iv:g6oeHIYGcfq4RrCfO/fm6LcfO9eag3D94PUAk70zhZg=,tag:3+16pK65akb78kjgcjyezQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
