apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZDNaUFdOcGVnNEJtVk9Y
            MnFIN0VjUUFUVkhUcElVSlhDLzlOeGp0ZkVZCmZJV0NtbDFWSmU0WHMrcUJYRVRa
            OWs1WFlpc3Fud0RBZ3hvTW1sWWQzeE0KLS0tICtwcms5SnBjTWtKVys0ZVBoWTdI
            Tm5GeFh1bThKNGgvVWd2SXJXU2d1NUUK7aBeX6HUPE4i2Sj6tL8nRK7Z6y58upca
            qsTgUjpQLUC2PYKCqJezY3sVwIAo6i7DgKFognafCOa8UlyvNQ3+fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-27T04:42:58Z"
    mac: ENC[AES256_GCM,data:7G0pyinSJkSQuJoq+AUXDUeTf12Y+aor4k/uPFI2PRnUEhbNqvqpyKhwjnv3bUP+DnbP2qP42NYvbxeOoFXRTWmsJVDxWmBcFP7lKsUzIG35uvyxBjPFaRYBMOmxcOBcxfpDYiCMwXGoJwZBdXaj45ZhbHfO2uLsYPf1+qioITU=,iv:sKhq9LoWAc3LjpWy+H3t1oYaLRjpMmOSyY6FHAjtPI0=,tag:Wcn7/VaWBhb03bA/sVO/8w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
