apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsMzNDUnVHOC9BYURpZ3Yr
            Mnl3MDhERkhFTnhPcmVHQUdmMzhiU0M3T1RzCkorNmZlOTIxUllqdHFHdGN1TWhv
            bTdJOWROeUtzS2VVQ05iS1lGZCtBSGsKLS0tIHdRUDFaYk0xYU9wa3VoNXdqUE04
            ODJZUllQQWtTek5mbzZkdWhGQjYrS3cKZZySr++djkKY1vbECx/yfTqcWwk1h0Wn
            VWf0rZ3miqTt7BubByZ6KHW6cX8FMVLqUrvuWtHOuysQGy0zJuO9bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T17:41:16Z"
    mac: ENC[AES256_GCM,data:2T27hSpz9+82E8wGd9DGo9AJcOk5o2N5UQ9zrKvWg7JonLS6sLZ+kuxnibeYry6V4nKRcIRP3Ep8iLkdtiBUzCHLdq/kQi1nwFQdzN/dSLmJHNkeJHoxUKB97ntetQUG2WJ2aChuTrzvNSLIxyitT3jSyJJD+LfHXHgtDXxbB+o=,iv:29iTtqCBGHWai6/33tKalZTLo/dFwP4D/BCfX/CCqJY=,tag:JQQUPxqxuTH/jIDqZxkQCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
