apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:FrM/JM9RjAztKWtuToDMR/7fEfemGs4VmomjMOmDiR6l8OU25EVZP5EAwtIwJqGVe8cRTIkzNZCVyEqR,iv:mQiC5F2jIA7Pg034XPVRoDPp0oBNVv+pMKdloPnvRmU=,tag:X7mZsBj8KQJnrGdQUcNQvQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcEw5dXY2RzBHaU5GNUFK
            VnpZekNEWVVBNmM3YVJVK3FPR0N2a3pHdndRCjdMNk9wMzBDTTZlYWlUOEFLMVl5
            aDE3V0JtTFFZcjc2TkQ3U0ZudE13L1kKLS0tIDVJTUg3c3k3R29nei9LT1lSYzAr
            RHRWVUgxUHFxaGtrdlNvVkFFeXVzRkEKOa0gutcS3NRvsVzpATyPLrNfKGO5cQfT
            eWWCpkevR2xaV52tR51A3ll6d8qcA7J+CB9sMjiCxxY6lkP6XpPotg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-20T05:21:42Z"
    mac: ENC[AES256_GCM,data:fplKO9IxqaL2vLcg2DuXnTRPD+L7x8ALFe1rdplttbeAH2D8HNfI4phNRE+d+aWu/FlXWL4KjVjOWwecxZxSIfxJqqhKZjHnxvlkv2WJ+QFxb+2Nee546P5nLl9zA98KBHo2xxpbjBe6carvliU0ckFU/LH9t07qH3egmg39oPA=,iv:w1neBMA71cJii/XsNKk7zEoyCH/nOFub+XlxrWB7D/M=,tag:hpiGNtn9RK5w7CbSDOXiww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
