apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:78Q9A/pHPEnkSiMcZMdkGbLttScMPN+G9hnAKrNCb4NhdYt71L0tjki3U4h/JAlYXzmQkvDp2o4o8bPh,iv:NPIaGB7QSzk/2PMezSJI7hlNzBokJlOjbYwk7MRCUCY=,tag:9WEWteY0iKn+eXmWIAif/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCcEw5dXY2RzBHaU5GNUFK
            VnpZekNEWVVBNmM3YVJVK3FPR0N2a3pHdndRCjdMNk9wMzBDTTZlYWlUOEFLMVl5
            aDE3V0JtTFFZcjc2TkQ3U0ZudE13L1kKLS0tIDVJTUg3c3k3R29nei9LT1lSYzAr
            RHRWVUgxUHFxaGtrdlNvVkFFeXVzRkEKOa0gutcS3NRvsVzpATyPLrNfKGO5cQfT
            eWWCpkevR2xaV52tR51A3ll6d8qcA7J+CB9sMjiCxxY6lkP6XpPotg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-20T04:33:58Z"
    mac: ENC[AES256_GCM,data:I9tb6lDs4sYZgIOxKbt8QdrCt+A2Lh1FKMLiKSVf7XXnqvoYyscwCLP7SsJdfrNEveefBmHSh2vjJbsFxLDohD3vdeDt0Ayd9ldYE1dhYTDluol75mGmSoKmohNjYrpZzAKsqhz0r2O/epvBj9mCNIqCHtLJgs6sol/F34eqkt4=,iv:/iqU+aFf3rHlZJ1NEWVUaDAuzFCG+A/TgmNjKljdiwU=,tag:6/iINPTCeqyd+pI41ZJ2VQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
