---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-operator
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 33.2.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
  install:
      createNamespace: true
      remediation:
        retries: 5
  upgrade:
    remediation:
      retries: 5
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  values:
    grafana:
      enabled: true
      env:
        GF_EXPLORE_ENABLED: true
        GF_PANELS_DISABLE_SANITIZE_HTML: true
        GF_LOG_FILTERS: rendering:debug
        GF_DATE_FORMATS_USE_BROWSER_LOCALE: true
        GF_DATE_FORMATS_FULL_DATE: "MMM Do, YYYY hh:mm:ss a"
        GF_DATE_FORMATS_INTERVAL_SECOND: "hh:mm:ss a"
        GF_DATE_FORMATS_INTERVAL_MINUTE: "hh:mm a"
        GF_DATE_FORMATS_INTERVAL_HOUR: "DD/MM hh:mm a"
        GF_DATE_FORMATS_INTERVAL_DAY: "DD/MM"
        GF_DATE_FORMATS_INTERVAL_MONTH: "MM-YYYY"
        GF_DATE_FORMATS_INTERVAL_YEAR: "YYYY"
      grafana.ini:
        server:
          root_url: "http://grafana.${DOMAIN_INTERNAL}"
      datasources:
        deleteDatasources:
        - name: Loki
          orgId: 1
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Prometheus
            type: prometheus
            url: http://prometheus-operator-kube-p-prometheus.monitoring:9090/
            access: proxy
            isDefault: true
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
      dashboards:
        default:
          # Ref: https://grafana.com/grafana/dashboards/12175
          calico-felix:
            gnetId: 12175
            revision: 5
            datasource: Prometheus 
          # Ref: https://grafana.com/grafana/dashboards/7845
          zfs:
            gnetId: 7845
            revision: 4
            datasource: Prometheus
          flux-cluster:
            url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/cluster.json
            datasource: Prometheus
          flux-control-plane:
            url: https://raw.githubusercontent.com/fluxcd/flux2/main/manifests/monitoring/grafana/dashboards/control-plane.json
            datasource: Prometheus
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "web"
        hosts:
          - "grafana.${DOMAIN_INTERNAL}"
    alertmanager:
      enabled: false
    prometheus:
      ingress:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "web"
        hosts:
          - "prometheus.${DOMAIN_INTERNAL}"
      prometheusSpec:
        replicas: 1
        retention: 7d