---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: flux-crds
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/crds
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
