apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
  namespace: monitoring
  labels:
    app:  prometheus-stack
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.10.10
    path: /mnt/Volume1/k3s
