---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-storage-pv
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      #version: 4.0.16
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
      interval: 5m
  values:
    nfs:
     server: 192.168.10.10
     path: /mnt/Volume2/kubernetes
    storageClass:
      name: nfs
      reclaimPolicy: Retain
      



