---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfs-storage-pv
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: 4.0.17
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    nfs:
      server: 192.168.10.10
      path: /mnt/Volume1/kubernetes
      mountOptions:
        - nfsvers=3
        - nolock
    storageClass:
      name: nfs
      reclaimPolicy: Retain
      



