apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZQJcHADGZxyrTGK4gx39Rw==,iv:GyRfbPZB2OXZv+AhyaNtw7fFVSSDFeBAeY5Jw638BT0=,tag:kVyhozeQx3ojPZ0QL8URjg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:ri7oO+zf46rcdBTP2Ec90/sVpbt+ig==,iv:bWf/VzDsT47q22Y3zlgEO7iJxgXUgmkXLGTyIwOZZ1c=,tag:EKOQOj045h+lp40/B6Imkg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUGhyWmZSc2xuY0pNZXFk
            Y2U3K0VNRHhSK1RnRThXcVVxSXU5eHR0dkQwCjlXQ1lhMjVjSlUwYVZ1N0xSWFpt
            MEt4NFhzQ1dHTW0wUGloN0NmV0VEY0kKLS0tIGlFTzNyZGRQay94OHoxdS9UbDlK
            Q29pMUtqdGt0YnN6QXBaajNFdzdIcFEK1Lotful7Xp+gQGCVqM0+xlWqT9O5JUZm
            wK4sYD5x2HFy/Wu+OEUafBmUEPAsswfq5nHFbsIllHXeawWh5OgT+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-25T17:41:15Z"
    mac: ENC[AES256_GCM,data:V3INGs3pY1TXjTu51BmHAwDRe9ApkDvsn5qw1Is4hkN8FjuJjgky8KRNG9rMpiuR1vUUSXNPEQQM6lyTFofCecaNQ7JaHFnQNrIopZHjlBsIqF77Fc49hMvW54d/p3RTDgcD5zC5ZbeJFa6Wm6CAW1uRObP58P6vRbKhKF5yEws=,iv:2poNAyu1qVzGs+iiuV3mG22ROS7mUB8TitMGNjqhwEM=,tag:mz7AiH/CdRtQoWO9BBPh3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
