apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:oA/jzVLx/i7HdjrQBwdp5g==,iv:TMRit/2sQeVRh1jsSLnQpuEqsypBKz+2vhEFZRjEalI=,tag:divL9WroEWvaV1DZCLddmg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:sQKmCxdd8cU1sFhUMh7+8yW8DjUx1w==,iv:t1ub9pCHosc0eaptGgJKXfvdYclrY0AYCipzqgxG+Yo=,tag:hiS2QQm+6KCUhI9TikkIPA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiRTVyVW56QStqeGpObkJX
            UG1maEZqd0hMbndIWHgvYzh6S2MwR25qOWl3CnNYTUFmbnl3TFBFSEpkajhQbnVn
            UGdoV2EvL1VZLzhuVlg0UHJZMFZON28KLS0tIFZ3YkdQYWlhWkM3VU9NSVEyay95
            elN4Y0kvY3BydGNYZFg0dXUwYWlKUHcKcMMlsArw49ZpYl6FOwPEQ7lHPn2OPGjM
            T7jY4Wm2nOPBXYJOQNndf/+ZGOFqbZe8Sp+0IDKoYlUEiuxxqp2HKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-04T07:16:55Z"
    mac: ENC[AES256_GCM,data:96H6hwk3IMXanJ1hkZvX4JAdL33exWZrvJXTOA6z8nGyQ1RY9+GQtsxwwxD0O3boXjHOJ/z1+nUowC09Dl3YhYJf94YaJwuBykQTRxn5OhNd7K5WAvD5V0k5nze0ruy9xlRQOocV9xZzkhjM1XRmPnJunXFBtxlU+TssTnDmP0k=,iv:fi+exGI9Or5V4rlq0yHMOo4j1MOGHbg66w+1YRh95KI=,tag:ucqyTgEn65Rv/In76R8+EA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
