apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:c4UcgxygOiRr3w1NtwzZdA==,iv:pNtPWU+IcqyBJLVkBNtVRtorWHGwmJ8FC31WCio/Ko8=,tag:pycAcysNb+rCQpofpm6XwQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Nlzy3UKzupIFMOcjSQWaJbUw0toWFA==,iv:yB24ivkw3Dxc5m4AfSvogPFm6Rt/0xbSHDIIC5ltsNw=,tag:r3lOXcW2pUvMtpzy2/L43g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSZTVlV0xGb01PR0k0T0tJ
            V09kd20rYWR5ZHhaTHlvMUtRZ1YyaURQQVQ0CkwxbnNRNHVrZkNrLzhrL3FsYVpS
            TGFXRFRDQStWdVFCa000MnZTTDhJV1kKLS0tIFUrY0FISU1ONncyK2R5a1Vac0dk
            b0VrZ2dXWUJYbmJKeXNrUTNIY3lQMG8Ki2hwi8KqaSY7etHmbNA0HTBzXfevLVo2
            Xh2cNJ7A/LuOA8sq+DJ5pSbqt74vFNdk9gLHLe3YH9AY9BG21bqqHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-25T07:23:45Z"
    mac: ENC[AES256_GCM,data:aw3GT9OgtpzYBFB1xoa2Faav3qMEVB5a515bOt05tVOcP9fFfXzMfki8I29nXmIVz+3nranRKcpKfBire+hNX8yh+CFfHhlmyULrEflUEr0CRMxSJReqAN97kLVd8UT/+wYyyoz8DKrLLKrk1P+wd+sl/eNIYxocNME0tEyFyes=,iv:WFSHNHBRB+xzwLP3IoKtx5XYkLD+CcMJPtezOAhrS3Q=,tag:EbmdjWjD3knPcdo/HaUCcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
