apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:ibcMluMNBhCF1F5V4bjx6g==,iv:LM1F82n3orjX91AICI37i2nWDd1cppVVEW1ijBvxu14=,tag:Wy4NdkzAYFgjhF8poLgzbg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:SYWd6+YoZlK6m591DWe2MzW0kiOhHg==,iv:Lrg1bdaPQU7E+WyS0D7ATeOYUQOJr0iU7qsDB9WdkSM=,tag:Gch/cR1tscLiJ6atlXYILg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4RC9XakJPYkVOaXlkeGFk
            bmllOGZOaDNaNVZpZFdSbStWK0Z2OElJVkdnCktxWFVWQlVpdTFBWWhJb1FYR2Nv
            STJIVnJxUW40U2lwVTV6bFQ4OTMwa28KLS0tIHhoVUtYK0VodzhBYVdjYytiZkFV
            dHAveDY3eU9MZFoyT2t0VThnMzJhWXcK1y8lpXqasIHw6dg/YNdsoGo9A2UpiHtw
            Ds2s8655Q3kQYQVLjBhBRYYanG4fUuCZnuFugnlijj20djvjSB7/TQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-22T06:56:09Z"
    mac: ENC[AES256_GCM,data:s7/JcxV+4Sa+yomMohQnZ8ZSM2w5+QUAHIjpEAy37zRFqHVftLuDg9NF7Ee28oPqFG+VPWzfqN2IJErIiYYeW5RII71LxmRxcBbDL2v0ndDeb4vdQ3RpOQjk+YJr+klZRFu4HeTXcNTSLE3+/8lSM/uH3L20TIcHR7myKx2q0r0=,iv:A+EYRnuhfZjrHhhrwKFE54EvcHRbIkB4biuhJ3wJmIA=,tag:Q65/dwi81JQzKhFns8BohA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
