---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./cloudflare-ddns/ks.yaml
  - ./external-dns/ks.yaml
  - ./ingress-nginx/ks.yaml
  - ./k8s-gateway/ks.yaml
  - ./metallb/ks.yaml
  - ./adguard-home/ks.yaml
