---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mayastor
  namespace: mayastor
spec:
  interval: 15m
  chart:
    spec:
      chart: mayastor
      version: 2.2.0
      sourceRef:
        kind: HelmRepository
        name: mayastor
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # -- Node labels for pod assignment
    # ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
    # Note that if multi-arch images support 'kubernetes.io/arch: amd64'
    # should be removed and set 'nodeSelector' to empty '{}' as default value.
    nodeSelector:
      kubernetes.io/arch: amd64

    metrics:
      # -- Enable the metrics exporter
      enabled: true
      # metrics refresh time
      # WARNING: Lowering pollingInterval value will affect performance adversely
      pollingInterval: "5m"
    loki-stack:
      enabled: false
    promtail:
      enabled: false
    ha:
      enabled: false

