---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
namespace: home-automation
resources:
  #- backups
  - ./helmrelease.yaml
  #- ./secret.sops.yaml
  #- ./token.sops.yaml
  - ./podmonitor.yaml
  #- ./volume.yaml
patchesStrategicMerge:
  - ./patches/addons.yaml
 # - ./patches/postgres.yaml
