---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: home-assistant
  namespace: home-automation
spec:
  podMetricsEndpoints:
    - interval: 1m
      path: /api/prometheus
      port: http
      scrapeTimeout: 30s
      bearerTokenSecret:
        name: home-automation
        key: prometheus-token
  selector:
    matchLabels:
      app.kubernetes.io/instance: home-assistant
      app.kubernetes.io/name: home-assistant
