---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dragonfly
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: ./contrib/charts/dragonfly
      version: 0.15.0
      sourceRef:
        kind: GitRepository
        name: dragonfly
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    interval: 2m
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: dragonfly-secret
