---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tvheadend
  namespace: media
spec:
  releaseName: tvheadend
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: tvheadend
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    nameOverride: tvheadend
    fullnameOverride: tvheadend
    hostNetwork: true
    nodeSelector:
      kubernetes.io/hostname: "k3s-worker-1"
    env:
      TZ: Europe/Berlin
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "web"
        hosts:
        - host: "tv.${DOMAIN_INTERNAL}"
    # persistence:
    #   config:
    #     enabled: false
    #     storageClass: nfs
    #     mountPath: /config
    #     accessMode: ReadWriteOnce
    #     size: 1Gi
    #   recordings:
    #     enabled: false
    #     storageClass: nfs
    #     mountPath: /recordings
    #     accessMode: ReadWriteOnce
    #     size: 300Gi

