---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-document-pv  
spec:
  storageClassName: nfs-document
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: ${NAS_IP}
    path: /mnt/Volume2/document
  mountOptions:
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-document-pvc
  namespace: document
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: nfs-document
  resources:
    requests:
      storage: 50Gi
