apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helm-release.yaml
configMapGenerator:
  - name: cabernet
    namespace: media
    files:
      - config/config.ini
generatorOptions:
  disableNameSuffixHash: true