# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Y3IVtgTu8Blp49Ou4wW91ZBYJUwxaCj+7rMsZ4pSTrpBWoBKjQA75Q==,iv:JkBS58Bfk1RsP5hPQz/PwAKPa3TKEJgpcMe/Uu8wfnE=,tag:GdlPYkyuYC3F0MHSCO7f2Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age12tjmxahz7dw8cravyesrycrazrzqkff03qk8hqnsrnsu5k3frdqskv4kcd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBenJ4dUUrallZTDhqMTAr
            bVZJSkwycXV3Y2gzNk56QmdkUElQbjljSEZjCkFxYUc0UEZpNExhTHVvZGNrdisv
            bVdGSk5HMUZZbzYySk5sZUovNEwrQ2sKLS0tIFBkVHdpdlgvbGJBT1c0c3dERXlB
            alNKczFxMkJXTUNVS3Z0NjNQbzFRLzAK6jiWaGA32MyNt/FuN7cCCShXgRlCEmAY
            TDgO6qbiCyVpSc/zihEJF/Yk0rbaW+S8gsq1GN2/TU6bVukYix/7GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-04T15:57:00Z"
    mac: ENC[AES256_GCM,data:2D82vtCCJiXAIg96M1I06uQduSSNxnmUMY1iNQvbA1Ta1Imf/UKiMZS1o9QOUSIhjq6K8oK5oNHdmy6Fxld06m7GYvikMMhqvotwjmV3Yh6FDjOkyE8Tlwo+gcA72gQyV0htV2k35fLa+XtYe2GhJ1wtI+IH0HQw/B9mw90JPq4=,iv:mybeL50lqf1wLK14D0Ira4R2RS6asOgwPtbdBbmcp/Y=,tag:YgEs3mIKtAA+Cy42OgBccA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
