---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:      
      - dns01:
          webhook:
            config:             
              authApiSecretRef: 
                name: godaddy-api-key
                key:  token
              production: true
              ttl: 600
            groupName: "acme.${SECRET_DOMAIN}"
            solverName: godaddy
        selector:          
          dnsZones:
            - "${SECRET_DOMAIN}."
