# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: godaddy-api-secret
    namespace: cert-manager
data:
    api-secret: ENC[AES256_GCM,data:Yx8DtY1K9hI+PViEAChoImZ4fiIzYtzSUmO7WsVdIQdigOIjHb6BWHKSSQWV,iv:DGIpEv2Jd0VRoP0P0ICSh6ahUwJGzzCioBjeEk0gETg=,tag:6CpMmTwsHZLATVYhyww8Lg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7dulnc9q3dsr6dfqgfec2mfufc0zckrntzqkfx8rvhzj9prfajq8jmztu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWHpzQzNMeVdCVlpwZFd3
            MGI4ZHBFcm5CVUJlcXlpMkUxRUEzMThOdlNnCk1MSCtESE5LTjVlRGxkK1Z3Rndi
            SXVCaWo2MDZ1MnJNdUlWYzlGWFpqalEKLS0tIE1DcmZRWnQ5SjJzbmNNMVJlWnRR
            d0krTzc5dEk4ZEFHTHViLzl1NER4WEEKzrYHO3BASHTWEwtVCyc7SQmMvHp/eTFa
            2Ez8jc1ANPsgDbpV1Z2LXoAqte/xgp3ue9GvLxt90N338Xjn9Jh1RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-21T10:24:12Z"
    mac: ENC[AES256_GCM,data:PamQJJpQFgi11ok6homZje/ykhoDsOsnvpDEPftgUQNThFDvnAwKBw5MatwbHkFK6WlprAc/4//6zDSmf4BQpFxyZpPd6OwdO+BYJqtfldsUr2kEdZ5vyxSSNvBnoiORDQBrcho8VVf0MQIc+spOmnXgqfe3yU+fterPAcM/gUk=,iv:z5e>    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1


