# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1l7dulnc9q3dsr6dfqgfec2mfufc0zckrntzqkfx8rvhzj9prfajq8jmztu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESDZ6MkNTWmNwZ2ZGWUZW
            NkdBNDBiRDRGSmp6RmVDdFJEYThPYnpDTkFNCm4vMkY4SnYxUzRGc1h6YzhvYlhE
            cHQ2WTJpYjR0bHVHWVBMaTVKTzVXUHMKLS0tIENKdGYyMVcvL0k1M2FMRkhIaWlq
            SnBuWnpqQTZQb2ZJSUNOeFlNM25kOFUK5/6BCH57j0n6W1hn9iL8seGu3UU3ZDy8
            w5bLka5OiOW6qh3UqzSkKfrpaYLkU5Fntl1GcvyevATi5lTX//vwSQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-12-18T07:04:21Z"
    mac: ENC[AES256_GCM,data:7i13CBYset9Vdww1UgIZba/L/RZeDZz7vfM0nysqWEd2FF6RZLFGrzdhLx6ZlUHR98x9xYD/FHc9JBDClncLxGQcIKEozGFwkkCBy8sUGhPaH7E0dzOR8AU/bFLk/iO5hUgc7/NFYTz776x6FIKPuN/fhQjYWBGamoAME6q+UhU=,iv:p+dN64OxUb5RttAgt8y/cNCMfAmkvTTXF6ZyOc4Epfo=,tag:wZWZa9qT528MiR8uHjFQqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
